#!/usr/bin/env bash
# generated by scripts/releasecheckgen.sh; do not edit by hand
# release-check provider: artifacts - generated code, docs, index, and artifact freshness
set -euo pipefail

bash scripts/lisp-rustgen.sh check
bash scripts/verificationdocgen.sh check
bash scripts/verificationcodegengen.sh check
bash scripts/gendocindex.sh check
cargo run -p dslraid-cli -- artifact verify examples/runscope/runscope.raid.json
