(in-package #:dslraid)

(load "lisp/tests/language.lisp")
(load "lisp/tests/language-duplicates.lisp")
(load "lisp/tests/language-references.lisp")
(load "lisp/tests/language-required.lisp")
(load "lisp/tests/language-identifiers.lisp")
(load "lisp/tests/language-malformed.lisp")
(load "lisp/tests/language-keywords.lisp")
(load "lisp/tests/language-booleans.lisp")
(load "lisp/tests/language-conformance.lisp")
(load "lisp/tests/collection-values.lisp")
(load "lisp/tests/enum-values.lisp")
(load "lisp/tests/source-values.lisp")
(load "lisp/tests/guard-action.lisp")
(load "lisp/tests/pipeline.lisp")

(defun run-golden-smoke ()
  (let ((fsms (runscope-fsms)))
    (run-language-smoke)
    (run-language-reference-smoke)
    (run-language-required-smoke)
    (run-language-identifier-smoke)
    (run-language-malformed-smoke)
    (run-language-keyword-smoke)
    (run-language-value-smoke)
    (run-language-collection-value-smoke)
    (run-language-enum-value-smoke)
    (run-language-enum-normalization-smoke)
    (run-language-source-value-smoke)
    (run-language-source-required-smoke)
    (run-language-source-range-smoke)
    (run-language-guard-action-identifier-smoke)
    (run-language-guard-action-duplicate-smoke)
    (run-language-guard-action-kind-smoke)
    (run-language-guard-action-expansion-smoke)
    (run-language-guard-action-expression-smoke)
    (run-language-boundary-smoke)
    (run-language-contract-smoke)
    (run-build-fsm-conformance-smoke)
    (dolist (fsm fsms)
      (assert (null (validate-fsm fsm))))
    (emit-project-json "runscope" "RunScope" fsms)))
