(in-package #:dslraid)

(load "lisp/tests/language.lisp")
(load "lisp/tests/collection-values.lisp")
(load "lisp/tests/enum-values.lisp")
(load "lisp/tests/source-values.lisp")

(defun run-golden-smoke ()
  (let ((fsms (runscope-fsms)))
    (run-language-smoke)
    (run-language-reference-smoke)
    (run-language-required-smoke)
    (run-language-identifier-smoke)
    (run-language-malformed-smoke)
    (run-language-keyword-smoke)
    (run-language-value-smoke)
    (run-language-collection-value-smoke)
    (run-language-enum-value-smoke)
    (run-language-enum-normalization-smoke)
    (run-language-source-value-smoke)
    (run-language-source-required-smoke)
    (run-language-source-range-smoke)
    (run-build-fsm-conformance-smoke)
    (dolist (fsm fsms)
      (assert (null (validate-fsm fsm))))
    (emit-project-json "runscope" "RunScope" fsms)))
