(in-package #:dslraid.agent)

(defun emit-agent-cluster-principles-markdown (&optional stream)
  "Emit deterministic Markdown for Agent Cluster operating principles."
  (let ((markdown (with-output-to-string (out)
                    (write-agent-principles-doc out))))
    (if stream
        (write-string markdown stream)
        markdown)))

(defun write-agent-principles-doc (out)
  (format out "# DSLRaid Agent Cluster Principles~%~%")
  (format out "<!-- generated by scripts/agentprinciplegen.sh; do not edit by hand -->~%~%")
  (format out "Source: `lisp/agent/principles.lisp`~%~%")
  (format out "Agent outputs are executable claims to verify, not authority.~%")
  (format out "Failures must become evidence, diagnostics, or generated knowledge updates.~%~%")
  (write-principle-table out)
  (write-bootloader-contract out))

(defun write-principle-table (out)
  (format out "## Control Surfaces~%~%")
  (format out "| Principle | Input | Output | Gate |~%")
  (format out "| --- | --- | --- | --- |~%")
  (dolist (row (agent-cluster-principle-catalog))
    (destructuring-bind (id input output gate) row
      (format out "| ~A | ~A | ~A | ~A |~%"
              id input output gate)))
  (terpri out))

(defun write-bootloader-contract (out)
  (format out "## Bootloader Contract~%~%")
  (format out "- Common Lisp forms are the executable knowledge surface.~%")
  (format out "- Canonical IR is the interchange product for Rust tooling.~%")
  (format out "- Go, Rust, TypeScript, Mermaid, DOT, SVG, and docs are generated artifacts.~%")
  (format out "- CI and sidecars produce evidence; they do not replace governance.~%"))
