(in-package #:dslraid.agent)

(defparameter *agent-cluster-principles*
  '(("evidence-before-change" "Observation / incident" "Evidence debt or linked evidence" "No speculative change without evidence, except emergency patches that create debt.")
    ("executable-knowledge" "Policy, DSL, schema, manifest, IR" "Generated docs and artifacts" "Human prose explains generated knowledge; it is not the SSOT.")
    ("versioned-ssot" "Context, ontology version, contract version" "Scoped authority" "SSOT authority is valid only inside an explicit context and version.")
    ("evidence-graph" "Raw evidence, interpretation, claim, artifact" "Traceable evidence links" "Unlinked evidence cannot justify high confidence or authority.")
    ("external-confidence" "Agent output and evidence graph" "Confidence ceiling" "Agent self-confidence is never final confidence.")
    ("verification-sidecar" "Producer output" "Independent verification evidence" "The producer and final verifier must be separate roles.")
    ("authority-gate" "Change candidate" "Approved, rejected, or escalated decision" "Agents may propose and verify, but governance owns authority.")
    ("access-policy" "Role and context" "RBAC, ABAC, and authority decision" "Capability does not imply permission; context still gates reasoning authority.")
    ("reliability-registry" "Agent run history" "Tier, confidence ceiling, and cold-start gate" "Agents are trusted by measured history, not by fluent claims.")
    ("cross-agent-agreement" "Producer and reviewers" "Isolated agreement with adversarial review" "Agreement is useful only when reviewers are independent and evidence-backed.")
    ("orchestration-manifest" "Control-plane routing decision" "Manifest receipt" "No orchestration is authoritative without policy, agent, evidence, and output records.")
    ("control-plane-verifier" "Orchestration decision and shadow route" "Independent sidecar verdict" "The control plane is routed and checked; it never verifies itself.")
    ("lease-and-abort" "Agent work lease" "Finished, rebase, abort, or escalate state" "Abort blocks authority; it never deletes evidence.")
    ("quarantine" "Suspicious output or tool behavior" "Isolated evidence bundle" "Quarantine blocks artifact commit, confidence increase, and automatic approval.")
    ("loss-ledger" "Cross-context translation" "Recorded semantic loss" "Lossy translation must declare what was lost; forbidden loss blocks promotion.")
    ("semantic-diff" "Generated artifact or SSOT change" "Meaning-level delta" "File diff is not enough; semantic hash and semantic diff drive review.")
    ("ssot-defect" "Official source defect candidate" "Freeze, migration, verification" "When the SSOT is wrong, affected outputs freeze before patching.")
    ("root-cause" "Observation and cause candidates" "Validated or eliminated cause set" "Root cause is confirmed by validation evidence, not asserted.")
    ("semantic-debugger" "Evidence graph and semantic versions" "Questions, missing evidence, and verification needs" "Semantic debugging proposes investigations; it does not declare the answer.")
    ("evidence-pruning" "Evidence retention or replacement request" "Tombstone and authority decision" "Evidence pruning changes memory, so protected evidence is retained and replacements leave tombstones.")
    ("security-audit" "Permission or security boundary change" "Policy, semantic hash, audit, approval, rollback" "Security changes start from policy and require audit evidence before deploy.")
    ("failure-conditions" "Operational breakage signal" "Blocked authority and response owner" "The system defines how it is failing, not only how it succeeds.")
    ("debt-register" "Unclosed learning gap" "Owner, repayment, and revalidation" "Debt is not failure, but invisible debt is failure.")
    ("review-capacity" "Human review queue" "Prioritized review or debt" "Human review is finite; overload freezes high-risk automation.")
    ("feedback-closure" "Failure, gap, or retrospective" "Policy, ontology, spec, owner, or revalidation update" "A loop that does not update knowledge remains open evidence.")))

(defun agent-cluster-principle-catalog ()
  "Return deterministic Agent Cluster operating principles."
  (copy-list *agent-cluster-principles*))
