(in-package #:dslraid.agent)

(defparameter *agent-cluster-principles*
  '(("evidence-before-change" "Observation / incident" "Evidence debt or linked evidence" "No speculative change without evidence, except emergency patches that create debt.")
    ("executable-knowledge" "Policy, DSL, schema, manifest, IR" "Generated docs and artifacts" "Human prose explains generated knowledge; it is not the SSOT.")
    ("bootstrap-sequence" "Language SSOT and generated files" "Checked IR, runtime, schema, tests, and pipelines" "The system boots from Lisp forms into file-backed evidence.")
    ("experiment-loop" "PDCA experiment record" "Reviewed evidence and promoted or rejected act" "Experiments are first-class evidence before policy.")
    ("merge-readiness" "Change candidate and generated gates" "Required merge gate evidence" "Autonomous merge is allowed only when privacy, quality, golden, and generated workflow gates pass.")
    ("merge-automation" "Pull request and workflow policy" "Readiness-gated automatic merge decision" "Automation may merge only through PR checks, read-only gates, and forbidden target-context execution.")
    ("branch-protection" "Main branch and required checks" "Protected merge contract" "Required checks are executable evidence, not repository folklore.")
    ("actions-receipt" "Remote workflow run" "Head SHA, conclusion, URL, and Pages receipt" "Remote CI success is accepted only as structured evidence.")
    ("source-shape" "Source files and public entrypoints" "75-line budget and minimal quality surface" "Complexity is managed by exposed surface, not by hiding file count.")
    ("objective-coverage" "Active goal requirements" "Tracked requirement-to-evidence map" "Goal progress stays inspectable without pretending the whole product is finished.")
    ("versioned-ssot" "Context, ontology version, contract version" "Scoped authority" "SSOT authority is valid only inside an explicit context and version.")
    ("evidence-graph" "Raw evidence, interpretation, claim, artifact" "Traceable evidence links" "Unlinked evidence cannot justify high confidence or authority.")
    ("evidence-ops" "CI, deploy, experiment, and incident loop" "Evidence graph update and conformance claim" "Operations are evidence generation, not mere automation.")
    ("external-confidence" "Agent output and evidence graph" "Confidence ceiling" "Agent self-confidence is never final confidence.")
    ("verification-sidecar" "Producer output" "Independent verification evidence" "The producer and final verifier must be separate roles.")
    ("authority-gate" "Change candidate" "Approved, rejected, or escalated decision" "Agents may propose and verify, but governance owns authority.")
    ("access-policy" "Role and context" "RBAC, ABAC, and authority decision" "Capability does not imply permission; context still gates reasoning authority.")
    ("reasoning-access" "Reasoning tier and domain context" "Allowed, blocked, or review-bound authority" "Higher reasoning means stronger verification, not automatic approval.")
    ("reliability-registry" "Agent run history" "Tier, confidence ceiling, and cold-start gate" "Agents are trusted by measured history, not by fluent claims.")
    ("cold-start-gate" "Unproven agent authority request" "Proposal, shadow, or bounded operation" "New agents must earn authority through evidence, not capability alone.")
    ("cross-agent-agreement" "Producer and reviewers" "Isolated agreement with adversarial review" "Agreement is useful only when reviewers are independent and evidence-backed.")
    ("adversarial-review" "High-risk claim or route" "Named failure probes and review evidence" "Adversarial review searches for ways the system can fail.")
    ("orchestration-manifest" "Control-plane routing decision" "Manifest receipt" "No orchestration is authoritative without policy, agent, evidence, and output records.")
    ("control-plane-verifier" "Orchestration decision and shadow route" "Independent sidecar verdict" "The control plane is routed and checked; it never verifies itself.")
    ("provider-compat" "Provider protocol and capabilities" "Compatible or blocked route" "Runtime providers are selected by proven capabilities, not by name.")
    ("runtime-trace" "Runtime event log and coverage overlay" "Design-linked execution evidence" "Executed transitions must map back to designed FSM subjects.")
    ("run-manifest" "Agent run unit" "Schema-valid run contract and generated doc" "Runs are file-backed evidence units, not transient logs.")
    ("adr-governance" "Semantic contract change" "ADR-required or autonomous boundary" "Core meaning changes require ADR; implementation internals may move.")
    ("backend-parity" "Verification graph projection" "Same-node backend evidence" "CI, local, and build-system surfaces must project the same graph.")
    ("github-actions-suite" "GitHub Actions surface" "Generated and curated workflow evidence" "Generated workflows and guard workflows both declare ownership and permissions.")
    ("release-provenance" "Release pipeline promotion" "Tag-bound gate evidence" "Release publishing requires generated workflow, tests, permissions, and provenance.")
    ("incident-learning" "Observed failure or drift" "Owner, knowledge update, revalidation, and prevention" "Incidents close only when the system learns in executable form.")
    ("genesis-charter" "Initial bounded responsibility record" "Purpose, assumptions, owner, risk boundary, and revalidation" "The first map is executable and review-owned, not prose authority.")
    ("meta-model" "Governance vocabulary" "Actor, artifact, evidence, claim, decision, risk, version, audit" "Rules about rules need explicit terms before automation can govern them.")
    ("backup-steward" "Missing or overloaded owner" "Temporary steward, forbidden actions, and review-back" "Backup authority keeps work moving without becoming permanent ownership.")
    ("revalidation-gate" "Knowledge freshness boundary" "Status, owner, blocked actions, and allowed work" "Revalidation date is an authority gate, not a reminder.")
    ("evidence-separation" "Raw evidence, interpretation, claim, artifact" "Separated evidence chain" "Observed facts, meaning, claims, and artifacts must not collapse into one object.")
    ("lease-and-abort" "Agent work lease" "Finished, rebase, abort, or escalate state" "Abort blocks authority; it never deletes evidence.")
    ("quarantine" "Suspicious output or tool behavior" "Isolated evidence bundle" "Quarantine blocks artifact commit, confidence increase, and automatic approval.")
    ("loss-ledger" "Cross-context translation" "Recorded semantic loss" "Lossy translation must declare what was lost; forbidden loss blocks promotion.")
    ("semantic-diff" "Generated artifact or SSOT change" "Meaning-level delta" "File diff is not enough; semantic hash and semantic diff drive review.")
    ("ssot-defect" "Official source defect candidate" "Freeze, migration, verification" "When the SSOT is wrong, affected outputs freeze before patching.")
    ("root-cause" "Observation and cause candidates" "Validated or eliminated cause set" "Root cause is confirmed by validation evidence, not asserted.")
    ("semantic-debugger" "Evidence graph and semantic versions" "Questions, missing evidence, and verification needs" "Semantic debugging proposes investigations; it does not declare the answer.")
    ("evidence-pruning" "Evidence retention or replacement request" "Tombstone and authority decision" "Evidence pruning changes memory, so protected evidence is retained and replacements leave tombstones.")
    ("security-audit" "Permission or security boundary change" "Policy, semantic hash, audit, approval, rollback" "Security changes start from policy and require audit evidence before deploy.")
    ("failure-conditions" "Operational breakage signal" "Blocked authority and response owner" "The system defines how it is failing, not only how it succeeds.")
    ("debt-register" "Unclosed learning gap" "Owner, repayment, and revalidation" "Debt is not failure, but invisible debt is failure.")
    ("incompleteness-ledger" "Unknown, gap, drift, or assumption" "Classified owner and authority effect" "Incomplete knowledge is allowed only when it is visible and owned.")
    ("review-capacity" "Human review queue" "Prioritized review or debt" "Human review is finite; overload freezes high-risk automation.")
    ("feedback-closure" "Failure, gap, or retrospective" "Policy, ontology, spec, owner, or revalidation update" "A loop that does not update knowledge remains open evidence.")))

(defun agent-cluster-principle-catalog ()
  "Return deterministic Agent Cluster operating principles."
  (copy-list *agent-cluster-principles*))
