(in-package #:dslraid.agent)

(defun emit-verification-bazel (&optional stream)
  "Emit Bazel genrules from the verification graph."
  (let ((text (with-output-to-string (out)
                (write-verification-bazel out))))
    (if stream
        (write-string text stream)
        text)))

(defun write-verification-bazel (out)
  (format out "# generated by scripts/bazelgen.sh; do not edit by hand~%")
  (format out "package(default_visibility = [\"//visibility:public\"])~%~%")
  (dolist (node (verification-nodes))
    (write-bazel-rule out node))
  (write-bazel-root out))

(defun write-bazel-rule (out node)
  (let ((id (verification-id node)))
    (format out "genrule(~%    name = \"~A\",~%" id)
    (write-bazel-srcs out node)
    (format out "    outs = [\"~A.stamp\"],~%" id)
    (format out "    cmd = \"~A && touch $@\",~%"
            (bazel-command-chain (verification-field node :commands)))
    (format out ")~%~%")))

(defun write-bazel-srcs (out node)
  (let ((needs (verification-field node :needs)))
    (when needs
      (format out "    srcs = [")
      (loop for need in needs
            for first = t then nil
            do (unless first (format out ", "))
               (format out "\":~A\"" need))
      (format out "],~%"))))

(defun write-bazel-root (out)
  (format out "genrule(~%    name = \"verify-daemon\",~%")
  (format out "    srcs = [\":release-check\"],~%")
  (format out "    outs = [\"verify-daemon.stamp\"],~%")
  (format out "    cmd = \"touch $@\",~%)~%"))

(defun bazel-command-chain (commands)
  (join-verification (mapcar #'bazel-escape-command commands) " && "))

(defun bazel-escape-command (command)
  (with-output-to-string (out)
    (loop for char across command
          do (case char
               (#\\ (write-string "\\\\" out))
               (#\" (write-string "\\\"" out))
               (#\$ (write-string "$$" out))
               (t (write-char char out))))))
