(in-package #:dslraid.agent)

(defun write-security-lines (out lines)
  (dolist (line lines)
    (format out "~A~%" line)))

(defun write-security-header (out)
  (write-security-lines
   out
   '("# generated by scripts/securityworkflowgen.sh; do not edit by hand"
     "name: Security"
     ""
     "on:"
     "  pull_request:"
     "  push:"
     "    branches: [main]"
     "  workflow_dispatch:"
     ""
     "permissions:"
     "  contents: read"
     "  security-events: write"
     ""
     "concurrency:"
     "  group: security-${{ github.ref }}"
     "  cancel-in-progress: true"
     ""
     "jobs:")))
