(in-package #:dslraid.agent)

(defparameter *verification-codegen-map*
  '(("code" ("rust-code"))
    ("docs" ("verification-doc" "docs-index"))
    ("schemas" ("evidence-schema" "manifest-schema"))
    ("tests" ("test-manifest"))
    ("conformance" ("conformance-report" "evidence-json"))
    ("github-actions" ("github-actions"))
    ("release-pipelines" ("github-release" "release-provenance"))
    ("pdca-evidence" ("pdca-manifest"))
    ("evidence-ops" ("evidence-ops"))
    ("loss-ledger" ("loss-ledger"))
    ("semantic-hash" ("semantic-hash"))
    ("semantic-diff" ("semantic-diff"))
    ("authority-gate" ("authority-manifest"))
    ("access-policy" ("access-policy"))
    ("reasoning-access" ("reasoning-access"))
    ("reliability-registry" ("reliability-registry"))
    ("cross-agent-agreement" ("agreement-manifest"))
    ("adversarial-review" ("adversarial-review"))
    ("evidence-quality" ("evidence-quality"))
    ("lease-and-abort" ("lease-manifest"))
    ("review-capacity" ("review-capacity"))
    ("feedback-closure" ("feedback-closure"))
    ("quarantine" ("quarantine-manifest"))
    ("external-confidence" ("confidence-manifest"))
    ("verification-sidecar" ("sidecar-manifest"))
    ("orchestration-manifest" ("orchestration-manifest"))
    ("control-plane-verifier" ("control-plane-verifier"))
    ("provider-compat" ("provider-compat"))
    ("runtime-trace" ("runtime-trace"))
    ("adr-governance" ("adr-governance"))
    ("backend-parity" ("backend-parity"))
    ("github-actions-suite" ("github-actions-suite"))
    ("evidence-before-change" ("evidence-before-change"))
    ("incident-learning" ("incident-learning"))
    ("genesis-charter" ("genesis-charter"))
    ("meta-model" ("meta-model"))
    ("backup-steward" ("backup-steward"))
    ("revalidation-gate" ("revalidation-gate"))
    ("cold-start-gate" ("cold-start-gate"))
    ("evidence-separation" ("evidence-separation"))
    ("versioned-ssot" ("versioned-ssot"))
    ("context-map" ("context-map"))
    ("historical-interpreter" ("historical-interpreter"))
    ("ontology-transition" ("ontology-transition"))
    ("ssot-defect" ("ssot-defect"))
    ("root-cause" ("root-cause"))
    ("semantic-debugger" ("semantic-debugger"))
    ("evidence-pruning" ("evidence-pruning"))
    ("security-audit" ("security-audit"))
    ("failure-conditions" ("failure-conditions"))
    ("debt-register" ("debt-register"))))

(defparameter *verification-codegen-rules*
  '(("codegen:axis-covered" "Every ontology codegen axis maps to a backend.")
    ("codegen:backend-checkable" "Every mapped backend has a check command.")))
