(in-package #:dslraid.agent)

(defun emit-verification-makefile (&optional stream)
  "Emit a local Makefile from the verification graph."
  (let ((text (with-output-to-string (out)
                (write-verification-makefile out))))
    (if stream
        (write-string text stream)
        text)))

(defun write-verification-makefile (out)
  (format out "# generated by scripts/makegen.sh; do not edit by hand~%")
  (format out ".PHONY: verify-daemon")
  (dolist (node (verification-nodes))
    (format out " ~A" (verification-id node)))
  (format out "~%~%verify-daemon: release-check~%~%")
  (loop for node in (verification-nodes)
        for first = t then nil
        do (unless first (terpri out))
           (write-make-target out node)))

(defun write-make-target (out node)
  (let ((id (verification-id node))
        (needs (verification-field node :needs)))
    (format out "~A:" id)
    (dolist (need needs)
      (format out " ~A" need))
    (terpri out)
    (dolist (command (verification-field node :commands))
      (format out "~C~A~%" #\Tab (make-escape-command command)))))

(defun make-escape-command (command)
  (with-output-to-string (out)
    (loop for char across command
          do (if (char= char #\$)
                 (write-string "$$" out)
                 (write-char char out)))))
