(in-package #:dslraid.agent)

(defun emit-verification-graph-markdown (&optional stream)
  "Emit deterministic Markdown for the verification graph."
  (let ((markdown (with-output-to-string (out)
                    (write-verification-graph-doc out))))
    (if stream
        (write-string markdown stream)
        markdown)))

(defun write-verification-graph-doc (out)
  (format out "# DSLRaid Verification Graph~%~%")
  (format out "<!-- generated by scripts/verificationdocgen.sh; do not edit by hand -->~%~%")
  (format out "Source: `lisp/agent/verification.lisp`~%~%")
  (format out "Form: `~A`~%~%" (getf (verification-graph) :form))
  (format out "CI is evidence generation, not final authority.~%")
  (format out "The generated workflow is `.github/workflows/verification.yml`.~%~%")
  (write-verification-table out)
  (write-verification-backends out)
  (write-pdca-loop out)
  (write-verification-contract out))

(defun write-verification-table (out)
  (format out "## Nodes~%~%")
  (format out "| Node | Needs | Evidence | Commands |~%")
  (format out "| --- | --- | --- | ---: |~%")
  (dolist (node (verification-nodes))
    (format out "| ~A | ~A | ~A | ~D |~%"
            (verification-id node)
            (join-verification (verification-field node :needs) ", ")
            (verification-field node :evidence)
            (length (verification-field node :commands)))))

(defun write-verification-backends (out)
  (format out "~%## Generated Backends~%~%")
  (format out "| Backend | Output | Generator |~%")
  (format out "| --- | --- | --- |~%")
  (dolist (row (verification-backends))
    (destructuring-bind (backend output generator) row
      (format out "| ~A | `~A` | `~A` |~%" backend output generator))))

(defun write-pdca-loop (out)
  (format out "~%## Evidence Loop~%~%")
  (format out "- Plan: edit the Common Lisp verification graph.~%")
  (format out "- Do: generate CI, release, local, and Bazel surfaces.~%")
  (format out "- Check: run generator checks and quality gates.~%")
  (format out "- Act: update the SSOT when a generated backend fails.~%"))

(defun write-verification-contract (out)
  (format out "~%## Contract~%~%")
  (format out "- Common Lisp is the executable verification SSOT.~%")
  (format out "- GitHub Actions YAML is generated evidence plumbing.~%")
  (format out "- Every generated workflow change must pass its generator check.~%")
  (format out "- Machine-readable evidence must pass verificationevidencegen check.~%")
  (format out "- Release checks must prove docs, workflows, and artifacts are fresh.~%"))

(defun join-verification (items separator)
  (if items
      (with-output-to-string (out)
        (loop for item in items
              for first = t then nil
              do (unless first (write-string separator out))
                 (write-string item out)))
      "none"))
