(in-package #:dslraid.agent)

(defvar *release-check-core-groups* nil)
(defvar *release-check-governance-groups* nil)
(defvar *release-check-runtime-groups* nil)
(defvar *release-check-ssot-groups* nil)
(defvar *release-check-artifact-groups* nil)

(defun verification-release-check-command-groups ()
  (append *release-check-core-groups*
          *release-check-governance-groups*
          *release-check-runtime-groups*
          *release-check-ssot-groups*
          *release-check-artifact-groups*))

(defun verification-release-check-commands ()
  "Return grouped release-check commands for generated verification surfaces."
  (cons "bash scripts/releasecheckgen.sh check"
        (mapcar #'release-check-wrapper-command
                (verification-release-check-command-groups))))

(defun release-check-wrapper-command (group)
  (format nil "bash ~A" (release-check-script-path (first group))))

(defun release-check-script-path (id)
  (format nil "scripts/releasecheck/~A.sh" id))

(defun verification-release-check-group-ids ()
  (mapcar #'first (verification-release-check-command-groups)))

(defun release-check-group-by-id (id)
  (find id (verification-release-check-command-groups)
        :test #'string= :key #'first))

(defun release-check-group-commands (group)
  (third group))

(defun emit-verification-release-check-script (id &optional stream)
  (let ((group (release-check-group-by-id id)))
    (unless group (error "Unknown release-check group: ~A" id))
    (let ((text (with-output-to-string (out)
                  (write-release-check-script out group))))
      (if stream (write-string text stream) text))))

(defun write-release-check-script (out group)
  (destructuring-bind (id purpose commands) group
    (format out "#!/usr/bin/env bash~%")
    (format out "# generated by scripts/releasecheckgen.sh; do not edit by hand~%")
    (format out "# release-check provider: ~A - ~A~%" id purpose)
    (format out "set -euo pipefail~%~%")
    (dolist (command commands)
      (format out "~A~%" command))))
