(in-package #:dslraid.agent)

(defun write-pages-lines (out lines)
  (dolist (line lines)
    (format out "~A~%" line)))

(defun write-pages-header (out)
  (write-pages-lines
   out
   '("# generated by scripts/pagesworkflowgen.sh; do not edit by hand"
     "name: Pages"
     ""
     "on:"
     "  push:"
     "    branches: [main]"
     "  workflow_dispatch:"
     ""
     "permissions:"
     "  contents: read"
     "  pages: write"
     "  id-token: write"
     ""
     "concurrency:"
     "  group: pages"
     "  cancel-in-progress: true"
     ""
     "jobs:")))
