(in-package #:dslraid.agent)

(defun emit-verification-gitlab-yaml (&optional stream)
  "Emit GitLab CI YAML from the verification graph."
  (let ((yaml (with-output-to-string (out)
                (write-verification-gitlab out))))
    (if stream
        (write-string yaml stream)
        yaml)))

(defun write-verification-gitlab (out)
  (format out "# generated by scripts/gitlabgen.sh; do not edit by hand~%")
  (format out "default:~%  image: rust:latest~%")
  (format out "  before_script:~%")
  (format out "    - apt-get update~%")
  (format out "    - apt-get install -y golang-go nodejs npm sbcl~%~%")
  (format out "stages:~%")
  (dolist (node (verification-nodes))
    (format out "  - ~A~%" (verification-id node)))
  (terpri out)
  (loop for node in (verification-nodes)
        for first = t then nil
        do (unless first (terpri out))
           (write-gitlab-job out node)))

(defun write-gitlab-job (out node)
  (let ((id (verification-id node)))
    (format out "~A:~%  stage: ~A~%" id id)
    (write-gitlab-needs out node)
    (format out "  script:~%")
    (dolist (command (verification-field node :commands))
      (format out "    - |~%      ~A~%" command))))

(defun write-gitlab-needs (out node)
  (let ((needs (verification-field node :needs)))
    (when needs
      (format out "  needs:~%")
      (dolist (need needs)
        (format out "    - ~A~%" need)))))
