(in-package #:dslraid.agent)

(defparameter *verification-release-check-commands*
  '("bash scripts/workflowgen.sh check"
    "bash scripts/gitlabgen.sh check"
    "bash scripts/makegen.sh check"
    "bash scripts/bazelgen.sh check"
    "bash scripts/releasegen.sh check"
    "bash scripts/privacycheck.sh check"
    "bash scripts/verificationprivacygen.sh check"
    "bash scripts/verificationpdcagen.sh check"
    "bash scripts/verificationlossgen.sh check"
    "bash scripts/verificationontologygen.sh check"
    "bash scripts/verificationconformancegen.sh check"
    "bash scripts/verificationschemagen.sh check"
    "bash scripts/verificationmanifestschemagen.sh check"
    "bash scripts/verificationtestgen.sh check"
    "bash scripts/verificationevidencegen.sh check"
    "bash scripts/verificationsemanticgen.sh check"
    "bash scripts/verificationdiffgen.sh check"
    "bash scripts/verificationauthoritygen.sh check"
    "bash scripts/verificationaccessgen.sh check"
    "bash scripts/verificationreliabilitygen.sh check"
    "bash scripts/verificationagreementgen.sh check"
    "bash scripts/verificationevidencequalitygen.sh check"
    "bash scripts/verificationleasegen.sh check"
    "bash scripts/verificationreviewgen.sh check"
    "bash scripts/verificationfeedbackgen.sh check"
    "bash scripts/verificationquarantinegen.sh check"
    "bash scripts/verificationconfidencegen.sh check"
    "bash scripts/verificationsidecargen.sh check"
    "bash scripts/verificationorchestrationgen.sh check"
    "bash scripts/verificationcontrolgen.sh check"
    "bash scripts/verificationprovidergen.sh check"
    "bash scripts/verificationruntimegen.sh check"
    "bash scripts/verificationadrgen.sh check"
    "bash scripts/verificationparitygen.sh check"
    "bash scripts/verificationactionsgen.sh check"
    "bash scripts/verificationevidencebeforechangegen.sh check"
    "bash scripts/verificationversionedssotgen.sh check"
    "bash scripts/verificationcontextmapgen.sh check"
    "bash scripts/verificationhistoricalgen.sh check"
    "bash scripts/verificationtransitiongen.sh check"
    "bash scripts/verificationssotdefectgen.sh check"
    "bash scripts/verificationrootcausegen.sh check"
    "bash scripts/verificationdebuggergen.sh check"
    "bash scripts/verificationpruninggen.sh check"
    "bash scripts/verificationsecuritygen.sh check"
    "bash scripts/verificationfailuregen.sh check"
    "bash scripts/verificationdebtgen.sh check"
    "bash scripts/lisp-rustgen.sh check"
    "bash scripts/verificationdocgen.sh check"
    "bash scripts/verificationcodegengen.sh check"
    "bash scripts/gendocindex.sh check"
    "cargo run -p dslraid-cli -- artifact verify examples/runscope/runscope.raid.json"))

(defun verification-release-check-commands ()
  "Return release-check commands for generated verification surfaces."
  *verification-release-check-commands*)
