(in-package #:dslraid.agent)

(defun write-ci-lines (out lines)
  (dolist (line lines)
    (format out "~A~%" line)))

(defun write-ci-header (out)
  (write-ci-lines
   out
   '("# generated by scripts/cigen.sh; do not edit by hand"
     "name: CI"
     ""
     "on:"
     "  pull_request:"
     "  push:"
     "    branches: [main]"
     "  workflow_dispatch:"
     ""
     "permissions:"
     "  contents: read"
     ""
     "concurrency:"
     "  group: ci-${{ github.ref }}"
     "  cancel-in-progress: true"
     ""
     "jobs:")))
