(in-package #:dslraid.agent)

(defparameter *verification-core-backends*
  '(("github-actions" ".github/workflows/verification.yml" "scripts/workflowgen.sh")
    ("github-ci" ".github/workflows/ci.yml" "scripts/cigen.sh")
    ("github-golden" ".github/workflows/golden.yml" "scripts/goldengen.sh")
    ("gitlab-ci" ".gitlab-ci.yml" "scripts/gitlabgen.sh")
    ("local-makefile" "Makefile" "scripts/makegen.sh")
    ("bazel" "BUILD.bazel" "scripts/bazelgen.sh")
    ("github-release" ".github/workflows/release.yml" "scripts/releasegen.sh")
    ("privacy-manifest" "docs/generated/verification-privacy.json" "scripts/verificationprivacygen.sh")
    ("pdca-manifest" "docs/generated/verification-pdca.json" "scripts/verificationpdcagen.sh")
    ("evidence-ops" "docs/generated/verification-evidence-ops.json" "scripts/verificationevidenceopsgen.sh")
    ("loss-ledger" "docs/generated/verification-loss-ledger.json" "scripts/verificationlossgen.sh")
    ("semantic-hash" "docs/generated/verification-semantic-hash.json" "scripts/verificationsemanticgen.sh")
    ("semantic-diff" "docs/generated/verification-semantic-diff.json" "scripts/verificationdiffgen.sh")
    ("authority-manifest" "docs/generated/verification-authority.json" "scripts/verificationauthoritygen.sh")
    ("access-policy" "docs/generated/verification-access-policy.json" "scripts/verificationaccessgen.sh")
    ("reasoning-access" "docs/generated/verification-reasoning-access.json" "scripts/verificationreasoninggen.sh")
    ("reliability-registry" "docs/generated/verification-reliability.json" "scripts/verificationreliabilitygen.sh")
    ("agreement-manifest" "docs/generated/verification-agreement.json" "scripts/verificationagreementgen.sh")
    ("adversarial-review" "docs/generated/verification-adversarial-review.json" "scripts/verificationadversarialgen.sh")
    ("evidence-quality" "docs/generated/verification-evidence-quality.json" "scripts/verificationevidencequalitygen.sh")
    ("lease-manifest" "docs/generated/verification-lease.json" "scripts/verificationleasegen.sh")
    ("review-capacity" "docs/generated/verification-review-capacity.json" "scripts/verificationreviewgen.sh")
    ("feedback-closure" "docs/generated/verification-feedback.json" "scripts/verificationfeedbackgen.sh")
    ("quarantine-manifest" "docs/generated/verification-quarantine.json" "scripts/verificationquarantinegen.sh")
    ("confidence-manifest" "docs/generated/verification-confidence.json" "scripts/verificationconfidencegen.sh")))
