(in-package #:dslraid.agent)

(defun emit-verification-workflow-yaml (&optional stream)
  "Emit GitHub Actions YAML from the verification graph."
  (let ((yaml (with-output-to-string (out)
                (write-verification-workflow out))))
    (if stream
        (write-string yaml stream)
        yaml)))

(defun write-verification-workflow (out)
  (format out "# generated by scripts/workflowgen.sh; do not edit by hand~%")
  (format out "name: Verification Graph~%~%")
  (format out "on:~%  pull_request:~%  push:~%    branches: [main]~%")
  (format out "  workflow_dispatch:~%~%permissions:~%  contents: read~%~%")
  (format out "concurrency:~%  group: verification-${{ github.ref }}~%")
  (format out "  cancel-in-progress: true~%~%jobs:~%")
  (loop for node in (verification-nodes)
        for first = t then nil
        do (unless first (terpri out))
           (write-verification-job out node)))

(defun write-verification-job (out node)
  (let ((id (verification-id node)))
    (format out "  ~A:~%    name: ~A~%" id (verification-field node :name))
    (format out "    runs-on: ubuntu-latest~%")
    (write-verification-needs out node)
    (format out "    steps:~%      - uses: actions/checkout@v6~%")
    (write-verification-tooling out node)
    (loop for command in (verification-field node :commands)
          for index from 1
          do (write-verification-command out id index command))))

(defun write-verification-needs (out node)
  (let ((needs (verification-field node :needs)))
    (when needs
      (format out "    needs: [~A]~%" (join-verification needs ", ")))))

(defun write-verification-tooling (out node)
  (let ((tooling (verification-field node :tooling)))
    (when (member :go tooling) (write-go-tooling out))
    (when (member :node tooling) (write-node-tooling out))
    (when (member :rust tooling) (write-rust-tooling out nil))
    (when (member :rust-lint tooling) (write-rust-tooling out t))
    (when (member :lisp tooling) (write-lisp-tooling out))))

(defun write-go-tooling (out)
  (format out "      - uses: actions/setup-go@v6~%")
  (format out "        with:~%          go-version: stable~%          cache: false~%"))

(defun write-node-tooling (out)
  (format out "      - uses: actions/setup-node@v6~%")
  (format out "        with:~%          node-version: 24~%")
  (format out "          cache: npm~%")
  (format out "          cache-dependency-path: apps/viewer/package-lock.json~%"))

(defun write-rust-tooling (out lint)
  (format out "      - uses: dtolnay/rust-toolchain@stable~%")
  (when lint
    (format out "        with:~%          components: rustfmt, clippy~%"))
  (format out "      - uses: Swatinem/rust-cache@v2~%"))

(defun write-lisp-tooling (out)
  (format out "      - name: Install SBCL~%")
  (format out "        run: bash scripts/install-sbcl.sh~%"))

(defun write-verification-command (out id index command)
  (format out "      - name: Run ~A command ~D~%" id index)
  (format out "        run: ~A~%" command))
