(in-package #:dslraid.agent)

(defparameter *verification-codegen-map*
  '(("language-expansion" ("language-expansion"))
    ("code" ("rust-code"))
    ("docs" ("verification-doc" "docs-index"))
    ("schemas" ("evidence-schema" "manifest-schema"))
    ("tests" ("test-manifest"))
    ("conformance" ("conformance-report" "evidence-json"))
    ("github-actions" ("github-actions" "github-ci" "github-golden" "github-security" "github-pages"))
    ("release-pipelines" ("github-release" "release-provenance" "release-check-providers"))
    ("bootstrap-sequence" ("bootstrap-sequence"))
    ("experiment-loop" ("experiment-loop" "experiment-decision"))
    ("merge-readiness" ("merge-readiness"))
    ("merge-automation" ("merge-automation"))
    ("branch-protection" ("branch-protection"))
    ("actions-receipt" ("actions-receipt" "merge-receipt"))
    ("source-shape" ("source-shape"))
    ("objective-coverage" ("objective-coverage"))
    ("pdca-evidence" ("pdca-manifest"))
    ("evidence-ops" ("evidence-ops" "evidence-graph"))
    ("loss-ledger" ("loss-ledger"))
    ("semantic-hash" ("semantic-hash"))
    ("semantic-diff" ("semantic-diff"))
    ("authority-gate" ("authority-manifest"))
    ("access-policy" ("access-policy" "public-projection"))
    ("reasoning-access" ("reasoning-access"))
    ("reliability-registry" ("reliability-registry"))
    ("cross-agent-agreement" ("agreement-manifest"))
    ("adversarial-review" ("adversarial-review"))
    ("evidence-quality" ("evidence-quality"))
    ("lease-and-abort" ("lease-manifest" "abort-evidence"))
    ("review-capacity" ("review-capacity"))
    ("feedback-closure" ("feedback-closure"))
    ("quarantine" ("quarantine-manifest" "quarantine-release"))
    ("external-confidence" ("confidence-manifest" "confidence-decision"))
    ("verification-sidecar" ("sidecar-manifest"))
    ("orchestration-manifest" ("orchestration-manifest"))
    ("control-plane-verifier" ("control-plane-verifier" "shadow-orchestrator"))
    ("provider-compat" ("provider-compat"))
    ("runtime-trace" ("runtime-trace"))
    ("runtime-contract" ("runtime-contract")) ("domain-fsm-dsl" ("domain-fsm-dsl")) ("semantic-os" ("semantic-os")) ("operating-loop" ("operating-loop"))
    ("run-manifest" ("run-manifest"))
    ("adr-governance" ("adr-governance"))
    ("backend-parity" ("backend-parity"))
    ("execution-projection" ("execution-projection"))
    ("github-actions-suite" ("github-actions-suite" "workflow-lineage"))
    ("evidence-before-change" ("evidence-before-change"))
    ("incident-learning" ("incident-learning")) ("governed-compiler-farm" ("governed-compiler-farm")) ("executable-knowledge" ("executable-knowledge"))
    ("learning-loop" ("learning-loop")) ("knowledge-conversion" ("knowledge-conversion"))
    ("quality-closure" ("quality-closure"))
    ("precommit-closure" ("precommit-closure"))
    ("genesis-charter" ("genesis-charter"))
    ("meta-model" ("meta-model"))
    ("backup-steward" ("backup-steward"))
    ("revalidation-gate" ("revalidation-gate"))
    ("cold-start-gate" ("cold-start-gate"))
    ("evidence-separation" ("evidence-separation"))
    ("versioned-ssot" ("versioned-ssot")) ("bounded-context" ("bounded-context"))
    ("context-map" ("context-map"))
    ("translation-verifier" ("translation-verifier"))
    ("historical-interpreter" ("historical-interpreter"))
    ("ontology-transition" ("ontology-transition"))
    ("ssot-defect" ("ssot-defect"))
    ("root-cause" ("root-cause"))
    ("semantic-debugger" ("semantic-debugger"))
    ("evidence-pruning" ("evidence-pruning"))
    ("security-audit" ("security-audit"))
    ("failure-conditions" ("failure-conditions" "failure-recovery"))
    ("debt-register" ("debt-register"))
    ("incompleteness-ledger" ("incompleteness-ledger"))))

(defparameter *verification-codegen-rules*
  '(("codegen:axis-covered" "Every ontology codegen axis maps to a backend.")
    ("codegen:backend-checkable" "Every mapped backend has a check command.")))
