(in-package #:dslraid.agent)

(defun emit-verification-release-yaml (&optional stream)
  "Emit GitHub release workflow YAML from the verification graph."
  (let ((yaml (with-output-to-string (out)
                (write-verification-release out))))
    (if stream
        (write-string yaml stream)
        yaml)))

(defun write-verification-release (out)
  (format out "# generated by scripts/releasegen.sh; do not edit by hand~%")
  (format out "name: Release~%~%")
  (format out "on:~%  push:~%    tags:~%      - 'v*'~%")
  (format out "  workflow_dispatch:~%~%permissions:~%  contents: write~%~%")
  (format out "jobs:~%  release:~%")
  (format out "    name: Create GitHub release~%")
  (format out "    runs-on: ubuntu-latest~%")
  (format out "    steps:~%")
  (write-release-checkout out)
  (write-release-rust-detect out)
  (write-release-rust-tooling out)
  (write-release-lisp-tooling out)
  (write-release-validation out)
  (write-release-create out))

(defun write-release-checkout (out)
  (format out "      - uses: actions/checkout@v6~%"))

(defun write-release-rust-detect (out)
  (format out "~A" "      - name: Detect Rust workspace
        id: rust
        run: |
          if [ -f Cargo.toml ]; then
            echo \"present=true\" >> \"$GITHUB_OUTPUT\"
          else
            echo \"present=false\" >> \"$GITHUB_OUTPUT\"
          fi
"))

(defun write-release-rust-tooling (out)
  (format out "      - uses: dtolnay/rust-toolchain@stable~%")
  (format out "        if: steps.rust.outputs.present == 'true'~%")
  (format out "      - uses: Swatinem/rust-cache@v2~%")
  (format out "        if: steps.rust.outputs.present == 'true'~%"))

(defun write-release-lisp-tooling (out)
  (format out "      - name: Install SBCL~%")
  (format out "        run: bash scripts/install-sbcl.sh~%"))

(defun write-release-validation (out)
  (format out "      - name: Test release build~%")
  (format out "        if: steps.rust.outputs.present == 'true'~%")
  (format out "        run: cargo test --workspace~%")
  (format out "      - name: Check generated release workflow~%")
  (format out "        run: bash scripts/releasegen.sh check~%"))

(defun write-release-create (out)
  (format out "      - name: Create release~%")
  (format out "        env:~%")
  (format out "          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}~%")
  (format out "        run: gh release create \"$GITHUB_REF_NAME\" --generate-notes~%"))
