(in-package #:dslraid.agent)

(defparameter *verification-tail-backends*
  '(("sidecar-manifest" "docs/generated/verification-sidecar.json" "scripts/verificationsidecargen.sh")
    ("orchestration-manifest" "docs/generated/verification-orchestration.json" "scripts/verificationorchestrationgen.sh")
    ("control-plane-verifier" "docs/generated/verification-control-plane.json" "scripts/verificationcontrolgen.sh")
    ("evidence-before-change" "docs/generated/verification-evidence-before-change.json" "scripts/verificationevidencebeforechangegen.sh")
    ("versioned-ssot" "docs/generated/verification-versioned-ssot.json" "scripts/verificationversionedssotgen.sh")
    ("context-map" "docs/generated/verification-context-map.json" "scripts/verificationcontextmapgen.sh")
    ("historical-interpreter" "docs/generated/verification-historical-interpreter.json" "scripts/verificationhistoricalgen.sh")
    ("ontology-transition" "docs/generated/verification-ontology-transition.json" "scripts/verificationtransitiongen.sh")
    ("ssot-defect" "docs/generated/verification-ssot-defect.json" "scripts/verificationssotdefectgen.sh")
    ("root-cause" "docs/generated/verification-root-cause.json" "scripts/verificationrootcausegen.sh")
    ("semantic-debugger" "docs/generated/verification-semantic-debugger.json" "scripts/verificationdebuggergen.sh")
    ("evidence-pruning" "docs/generated/verification-pruning.json" "scripts/verificationpruninggen.sh")
    ("security-audit" "docs/generated/verification-security-audit.json" "scripts/verificationsecuritygen.sh")
    ("failure-conditions" "docs/generated/verification-failure-conditions.json" "scripts/verificationfailuregen.sh")
    ("debt-register" "docs/generated/verification-debt.json" "scripts/verificationdebtgen.sh")
    ("rust-code" "generated/runtime_fsm.rs" "scripts/lisp-rustgen.sh")
    ("verification-doc" "docs/generated/verification-graph.md" "scripts/verificationdocgen.sh")
    ("docs-index" "docs/generated/generated-docs.md" "scripts/gendocindex.sh")
    ("codegen-map" "docs/generated/verification-codegen.json" "scripts/verificationcodegengen.sh")
    ("ontology-manifest" "docs/generated/verification-ontology.json" "scripts/verificationontologygen.sh")
    ("conformance-report" "docs/generated/verification-conformance.json" "scripts/verificationconformancegen.sh")
    ("evidence-schema" "schemas/dslraid-verification-evidence.schema.json" "scripts/verificationschemagen.sh")
    ("manifest-schema" "schemas/dslraid-verification-manifest.schema.json" "scripts/verificationmanifestschemagen.sh")
    ("test-manifest" "tests/golden/verification-graph.generated.json" "scripts/verificationtestgen.sh")
    ("evidence-json" "docs/generated/verification-evidence.json" "scripts/verificationevidencegen.sh")))
