(in-package #:dslraid.agent)

(defun verification-manifest-schema-runtime-defs-json ()
  (concatenate
   'string
   "\"failure_condition\":{\"type\":\"object\",\"required\":[\"id\",\"domain\",\"signal\",\"severity\",\"blocks\",\"evidence\",\"response\",\"owner\",\"meaning\"],\"additionalProperties\":false,\"properties\":{\"id\":{\"$ref\":\"#/$defs/semantic_ref\"},\"domain\":{\"enum\":[\"ontology\",\"confidence\",\"reviewer\",\"control-plane\",\"lease\",\"translation\",\"evidence-quality\",\"feedback\"]},\"signal\":{\"type\":\"string\",\"minLength\":1},\"severity\":{\"enum\":[\"error\",\"warning\",\"info\"]},\"blocks\":{\"$ref\":\"#/$defs/strings\"},\"evidence\":{\"$ref\":\"#/$defs/strings\"},\"response\":{\"$ref\":\"#/$defs/semantic_ref\"},\"owner\":{\"$ref\":\"#/$defs/semantic_ref\"},\"meaning\":{\"type\":\"string\",\"minLength\":1}}},"
   "\"control_plane_verification\":{\"type\":\"object\",\"required\":[\"id\",\"route\",\"control_plane\",\"verifier\",\"shadow\",\"divergence\",\"severity\",\"authority\",\"evidence\",\"meaning\"],\"additionalProperties\":false,\"properties\":{\"id\":{\"$ref\":\"#/$defs/semantic_ref\"},\"route\":{\"$ref\":\"#/$defs/semantic_ref\"},\"control_plane\":{\"$ref\":\"#/$defs/semantic_ref\"},\"verifier\":{\"$ref\":\"#/$defs/semantic_ref\"},\"shadow\":{\"$ref\":\"#/$defs/semantic_ref\"},\"divergence\":{\"enum\":[\"D0\",\"D1\",\"D2\",\"D3\",\"D4\"]},\"severity\":{\"enum\":[\"none\",\"review\",\"human-review\",\"authority-blocked\"]},\"authority\":{\"$ref\":\"#/$defs/semantic_ref\"},\"evidence\":{\"$ref\":\"#/$defs/strings\"},\"meaning\":{\"type\":\"string\",\"minLength\":1}}},"
   "\"shadow_orchestrator_record\":{\"type\":\"object\",\"required\":[\"id\",\"route\",\"primary\",\"shadow\",\"divergence\",\"action\",\"evidence\",\"meaning\"],\"additionalProperties\":false,\"properties\":{\"id\":{\"$ref\":\"#/$defs/semantic_ref\"},\"route\":{\"$ref\":\"#/$defs/semantic_ref\"},\"primary\":{\"$ref\":\"#/$defs/semantic_ref\"},\"shadow\":{\"$ref\":\"#/$defs/semantic_ref\"},\"divergence\":{\"enum\":[\"D0\",\"D1\",\"D2\",\"D3\",\"D4\"]},\"action\":{\"enum\":[\"observe\",\"human-review\",\"authority-blocked\"]},\"evidence\":{\"$ref\":\"#/$defs/strings\"},\"meaning\":{\"type\":\"string\",\"minLength\":1}}},"
   "\"provider_compat_record\":{\"type\":\"object\",\"required\":[\"id\",\"provider\",\"runtime\",\"protocol\",\"requires\",\"supports\",\"status\",\"evidence\",\"meaning\"],\"additionalProperties\":false,\"properties\":{\"id\":{\"$ref\":\"#/$defs/semantic_ref\"},\"provider\":{\"$ref\":\"#/$defs/semantic_ref\"},\"runtime\":{\"$ref\":\"#/$defs/semantic_ref\"},\"protocol\":{\"$ref\":\"#/$defs/semantic_ref\"},\"requires\":{\"$ref\":\"#/$defs/strings\"},\"supports\":{\"$ref\":\"#/$defs/strings\"},\"status\":{\"enum\":[\"compatible\",\"blocked\"]},\"evidence\":{\"$ref\":\"#/$defs/strings\"},\"meaning\":{\"type\":\"string\",\"minLength\":1}}},"
   "\"runtime_trace_mapping\":{\"type\":\"object\",\"required\":[\"id\",\"design_ir\",\"trace\",\"coverage\",\"runtime_subject\",\"design_subject\",\"coverage_status\",\"evidence\",\"meaning\"],\"additionalProperties\":false,\"properties\":{\"id\":{\"$ref\":\"#/$defs/semantic_ref\"},\"design_ir\":{\"$ref\":\"#/$defs/path\"},\"trace\":{\"$ref\":\"#/$defs/path\"},\"coverage\":{\"$ref\":\"#/$defs/path\"},\"runtime_subject\":{\"$ref\":\"#/$defs/semantic_ref\"},\"design_subject\":{\"$ref\":\"#/$defs/semantic_ref\"},\"coverage_status\":{\"enum\":[\"covered\",\"uncovered\",\"failed\"]},\"evidence\":{\"$ref\":\"#/$defs/strings\"},\"meaning\":{\"type\":\"string\",\"minLength\":1}}},"
   "\"domain_fsm_surface\":{\"type\":\"object\",\"required\":[\"id\",\"kind\",\"source\",\"generated\",\"command\",\"assertion\",\"lossy\",\"evidence\",\"meaning\"],\"additionalProperties\":false,\"properties\":{\"id\":{\"$ref\":\"#/$defs/semantic_ref\"},\"kind\":{\"enum\":[\"lisp-dsl\",\"canonical-ir\",\"runtime-code\",\"human-diagram\"]},\"source\":{\"type\":\"string\",\"minLength\":1},\"generated\":{\"$ref\":\"#/$defs/strings\"},\"command\":{\"type\":\"string\",\"minLength\":1},\"assertion\":{\"type\":\"string\",\"pattern\":\"^stdout:.+\"},\"lossy\":{\"type\":\"boolean\"},\"evidence\":{\"$ref\":\"#/$defs/strings\"},\"meaning\":{\"type\":\"string\",\"minLength\":1}}},"
   "\"semantic_os_layer\":{\"type\":\"object\",\"required\":[\"id\",\"role\",\"os_layer\",\"source\",\"artifact\",\"command\",\"assertion\",\"evidence\",\"authority\",\"meaning\"],\"additionalProperties\":false,\"properties\":{\"id\":{\"$ref\":\"#/$defs/semantic_ref\"},\"role\":{\"enum\":[\"firmware\",\"kernel\",\"filesystem\",\"userland\",\"driver\",\"log\",\"scheduler\",\"court\"]},\"os_layer\":{\"type\":\"string\",\"minLength\":1},\"source\":{\"$ref\":\"#/$defs/path\"},\"artifact\":{\"$ref\":\"#/$defs/path\"},\"command\":{\"type\":\"string\",\"minLength\":1},\"assertion\":{\"type\":\"string\",\"pattern\":\"^stdout:.+\"},\"evidence\":{\"$ref\":\"#/$defs/strings\"},\"authority\":{\"$ref\":\"#/$defs/semantic_ref\"},\"meaning\":{\"type\":\"string\",\"minLength\":1}}},"
   "\"operating_loop_stage\":{\"type\":\"object\",\"required\":[\"order\",\"id\",\"phase\",\"input\",\"output\",\"command\",\"assertion\",\"gate\",\"evidence\",\"meaning\"],\"additionalProperties\":false,\"properties\":{\"order\":{\"type\":\"integer\",\"minimum\":1},\"id\":{\"$ref\":\"#/$defs/semantic_ref\"},\"phase\":{\"type\":\"string\",\"minLength\":1},\"input\":{\"$ref\":\"#/$defs/path\"},\"output\":{\"$ref\":\"#/$defs/path\"},\"command\":{\"type\":\"string\",\"minLength\":1},\"assertion\":{\"type\":\"string\",\"pattern\":\"^stdout:.+\"},\"gate\":{\"$ref\":\"#/$defs/semantic_ref\"},\"evidence\":{\"$ref\":\"#/$defs/strings\"},\"meaning\":{\"type\":\"string\",\"minLength\":1}}},"
   "\"knowledge_conversion_step\":{\"type\":\"object\",\"required\":[\"order\",\"id\",\"phase\",\"input\",\"output\",\"command\",\"assertion\",\"gate\",\"evidence\",\"meaning\"],\"additionalProperties\":false,\"properties\":{\"order\":{\"type\":\"integer\",\"minimum\":1},\"id\":{\"$ref\":\"#/$defs/semantic_ref\"},\"phase\":{\"type\":\"string\",\"minLength\":1},\"input\":{\"$ref\":\"#/$defs/path\"},\"output\":{\"$ref\":\"#/$defs/path\"},\"command\":{\"type\":\"string\",\"minLength\":1},\"assertion\":{\"type\":\"string\",\"pattern\":\"^stdout:.+\"},\"gate\":{\"$ref\":\"#/$defs/semantic_ref\"},\"evidence\":{\"$ref\":\"#/$defs/strings\"},\"meaning\":{\"type\":\"string\",\"minLength\":1}}},"
   "\"backend_parity_projection\":{\"type\":\"object\",\"required\":[\"id\",\"backend\",\"output\",\"generator\",\"projection\",\"graph_nodes\",\"check\",\"meaning\"],\"additionalProperties\":false,\"properties\":{\"id\":{\"$ref\":\"#/$defs/semantic_ref\"},\"backend\":{\"type\":\"string\",\"minLength\":1},\"output\":{\"$ref\":\"#/$defs/path\"},\"generator\":{\"$ref\":\"#/$defs/path\"},\"projection\":{\"type\":\"string\",\"minLength\":1},\"graph_nodes\":{\"$ref\":\"#/$defs/strings\"},\"check\":{\"type\":\"string\",\"pattern\":\"^scripts/.+ check$\"},\"meaning\":{\"type\":\"string\",\"minLength\":1}}},"
   "\"github_actions_workflow\":{\"type\":\"object\",\"required\":[\"id\",\"workflow\",\"role\",\"generated\",\"generator\",\"permissions\",\"evidence\",\"meaning\"],\"additionalProperties\":false,\"properties\":{\"id\":{\"$ref\":\"#/$defs/semantic_ref\"},\"workflow\":{\"$ref\":\"#/$defs/path\"},\"role\":{\"type\":\"string\",\"minLength\":1},\"generated\":{\"type\":\"boolean\"},\"generator\":{\"type\":\"string\",\"minLength\":1},\"permissions\":{\"$ref\":\"#/$defs/strings\"},\"evidence\":{\"$ref\":\"#/$defs/strings\"},\"meaning\":{\"type\":\"string\",\"minLength\":1}}},"
   "\"workflow_lineage_record\":{\"type\":\"object\",\"required\":[\"id\",\"surface\",\"graph_nodes\",\"artifact\",\"generator\",\"check\",\"evidence\",\"status\",\"meaning\"],\"additionalProperties\":false,\"properties\":{\"id\":{\"$ref\":\"#/$defs/semantic_ref\"},\"surface\":{\"enum\":[\"github-actions\",\"gitlab-ci\",\"local-makefile\",\"bazel\",\"release-check-provider\"]},\"graph_nodes\":{\"$ref\":\"#/$defs/strings\"},\"artifact\":{\"$ref\":\"#/$defs/path\"},\"generator\":{\"$ref\":\"#/$defs/path\"},\"check\":{\"type\":\"string\",\"pattern\":\"^scripts/.+ check$\"},\"evidence\":{\"$ref\":\"#/$defs/strings\"},\"status\":{\"const\":\"generated\"},\"meaning\":{\"type\":\"string\",\"minLength\":1}}},"
   "\"experiment_decision_record\":{\"type\":\"object\",\"required\":[\"id\",\"experiment\",\"decision\",\"gate\",\"act\",\"evidence\",\"status\",\"meaning\"],\"additionalProperties\":false,\"properties\":{\"id\":{\"$ref\":\"#/$defs/semantic_ref\"},\"experiment\":{\"$ref\":\"#/$defs/semantic_ref\"},\"decision\":{\"enum\":[\"promote\",\"hold\",\"reject\"]},\"gate\":{\"$ref\":\"#/$defs/semantic_ref\"},\"act\":{\"$ref\":\"#/$defs/path\"},\"evidence\":{\"$ref\":\"#/$defs/strings\"},\"status\":{\"enum\":[\"open\",\"closed\"]},\"meaning\":{\"type\":\"string\",\"minLength\":1}}},"
   "\"release_provenance_gate\":{\"type\":\"object\",\"required\":[\"id\",\"gate\",\"workflow\",\"requires\",\"evidence\",\"status\",\"meaning\"],\"additionalProperties\":false,\"properties\":{\"id\":{\"$ref\":\"#/$defs/semantic_ref\"},\"gate\":{\"type\":\"string\",\"minLength\":1},\"workflow\":{\"$ref\":\"#/$defs/path\"},\"requires\":{\"$ref\":\"#/$defs/strings\"},\"evidence\":{\"$ref\":\"#/$defs/strings\"},\"status\":{\"const\":\"required\"},\"meaning\":{\"type\":\"string\",\"minLength\":1}}},"))
