(in-package #:dslraid.agent)

(defun verification-manifest-schema-governance-defs-json ()
  (concatenate
   'string
   "\"authority_decision\":{\"type\":\"object\",\"required\":[\"id\",\"scope\",\"decision\",\"approved_by\",\"requires\",\"evidence\",\"meaning\"],\"additionalProperties\":false,\"properties\":{\"id\":{\"$ref\":\"#/$defs/semantic_ref\"},\"scope\":{\"enum\":[\"routine\",\"release\",\"security\",\"audit\",\"ontology\",\"incident\"]},\"decision\":{\"enum\":[\"approved\",\"escalated\",\"rejected\"]},\"approved_by\":{\"$ref\":\"#/$defs/semantic_ref\"},\"requires\":{\"$ref\":\"#/$defs/strings\"},\"evidence\":{\"$ref\":\"#/$defs/strings\"},\"meaning\":{\"type\":\"string\",\"minLength\":1}}},"
   "\"access_policy\":{\"type\":\"object\",\"required\":[\"id\",\"role\",\"context\",\"decision\",\"rbac\",\"abac\",\"evidence\",\"authority\",\"meaning\"],\"additionalProperties\":false,\"properties\":{\"id\":{\"$ref\":\"#/$defs/semantic_ref\"},\"role\":{\"enum\":[\"producer\",\"verifier\",\"steward\",\"governance\"]},\"context\":{\"enum\":[\"public-surface\",\"private-data\",\"security-boundary\",\"release\",\"ontology\"]},\"decision\":{\"enum\":[\"allow\",\"deny\",\"escalate\"]},\"rbac\":{\"$ref\":\"#/$defs/semantic_ref\"},\"abac\":{\"$ref\":\"#/$defs/semantic_ref\"},\"evidence\":{\"$ref\":\"#/$defs/strings\"},\"authority\":{\"$ref\":\"#/$defs/semantic_ref\"},\"meaning\":{\"type\":\"string\",\"minLength\":1}}},"
   "\"reasoning_access_record\":{\"type\":\"object\",\"required\":[\"id\",\"agent\",\"reasoning_tier\",\"context\",\"abac\",\"authority_effect\",\"confidence_ceiling\",\"allowed\",\"blocked\",\"evidence\",\"owner\",\"meaning\"],\"additionalProperties\":false,\"properties\":{\"id\":{\"$ref\":\"#/$defs/semantic_ref\"},\"agent\":{\"$ref\":\"#/$defs/semantic_ref\"},\"reasoning_tier\":{\"enum\":[\"R0\",\"R1\",\"R2\",\"R3\",\"R4\"]},\"context\":{\"enum\":[\"verification\",\"public-surface\",\"incident\",\"ontology\",\"release\",\"security-boundary\"]},\"abac\":{\"$ref\":\"#/$defs/semantic_ref\"},\"authority_effect\":{\"enum\":[\"transform-only\",\"analysis-only\",\"human-review\",\"governance-review\",\"blocked\"]},\"confidence_ceiling\":{\"enum\":[\"low\",\"medium\",\"high\"]},\"allowed\":{\"$ref\":\"#/$defs/strings\"},\"blocked\":{\"$ref\":\"#/$defs/strings\"},\"evidence\":{\"$ref\":\"#/$defs/strings\"},\"owner\":{\"$ref\":\"#/$defs/semantic_ref\"},\"meaning\":{\"type\":\"string\",\"minLength\":1}}},"
   "\"adversarial_probe\":{\"type\":\"object\",\"required\":[\"id\",\"scope\",\"reviewer\",\"probe\",\"severity\",\"detects\",\"evidence\",\"authority_effect\",\"owner\",\"meaning\"],\"additionalProperties\":false,\"properties\":{\"id\":{\"$ref\":\"#/$defs/semantic_ref\"},\"scope\":{\"enum\":[\"release\",\"conformance\",\"authority\",\"experiment\"]},\"reviewer\":{\"$ref\":\"#/$defs/semantic_ref\"},\"probe\":{\"type\":\"string\",\"minLength\":1},\"severity\":{\"enum\":[\"D0\",\"D1\",\"D2\",\"D3\",\"D4\"]},\"detects\":{\"$ref\":\"#/$defs/strings\"},\"evidence\":{\"$ref\":\"#/$defs/strings\"},\"authority_effect\":{\"enum\":[\"review-required\",\"human-review\",\"authority-blocked\"]},\"owner\":{\"$ref\":\"#/$defs/semantic_ref\"},\"meaning\":{\"type\":\"string\",\"minLength\":1}}},"
   "\"incomplete_unknown\":{\"type\":\"object\",\"required\":[\"id\",\"unknown_kind\",\"domain\",\"source\",\"status\",\"owner\",\"next_action\",\"authority_effect\",\"evidence\",\"meaning\"],\"additionalProperties\":false,\"properties\":{\"id\":{\"$ref\":\"#/$defs/semantic_ref\"},\"unknown_kind\":{\"enum\":[\"unknown\",\"gap\",\"drift\",\"assumption\"]},\"domain\":{\"type\":\"string\",\"minLength\":1},\"source\":{\"$ref\":\"#/$defs/path\"},\"status\":{\"enum\":[\"open\",\"triaged\",\"closed\"]},\"owner\":{\"$ref\":\"#/$defs/semantic_ref\"},\"next_action\":{\"type\":\"string\",\"minLength\":1},\"authority_effect\":{\"enum\":[\"authority-blocked\",\"review-required\",\"human-review\"]},\"evidence\":{\"$ref\":\"#/$defs/strings\"},\"meaning\":{\"type\":\"string\",\"minLength\":1}}},"
   "\"reliability_record\":{\"type\":\"object\",\"required\":[\"id\",\"agent\",\"tier\",\"status\",\"confidence_ceiling\",\"failure_rate\",\"verification_rate\",\"authority_effect\",\"evidence\",\"restrictions\",\"meaning\"],\"additionalProperties\":false,\"properties\":{\"id\":{\"$ref\":\"#/$defs/semantic_ref\"},\"agent\":{\"$ref\":\"#/$defs/semantic_ref\"},\"tier\":{\"enum\":[\"T0\",\"T1\",\"T2\",\"T3\",\"T4\"]},\"status\":{\"enum\":[\"candidate\",\"shadow\",\"assisted\",\"bounded\",\"trusted\"]},\"confidence_ceiling\":{\"enum\":[\"low\",\"medium\",\"high\"]},\"failure_rate\":{\"type\":\"integer\",\"minimum\":0,\"maximum\":100},\"verification_rate\":{\"type\":\"integer\",\"minimum\":0,\"maximum\":100},\"authority_effect\":{\"enum\":[\"authority-blocked\",\"human-review\",\"bounded-auto\",\"trusted-context\"]},\"evidence\":{\"$ref\":\"#/$defs/strings\"},\"restrictions\":{\"$ref\":\"#/$defs/strings\"},\"meaning\":{\"type\":\"string\",\"minLength\":1}}},"
   "\"agreement_record\":{\"type\":\"object\",\"required\":[\"id\",\"producer\",\"reviewers\",\"risk\",\"decision\",\"isolation\",\"ontology\",\"adversarial\",\"evidence\",\"meaning\"],\"additionalProperties\":false,\"properties\":{\"id\":{\"$ref\":\"#/$defs/semantic_ref\"},\"producer\":{\"$ref\":\"#/$defs/semantic_ref\"},\"reviewers\":{\"$ref\":\"#/$defs/strings\"},\"risk\":{\"enum\":[\"routine\",\"high\",\"audit\"]},\"decision\":{\"enum\":[\"agree\",\"blocked\"]},\"isolation\":{\"enum\":[\"sealed\",\"open\"]},\"ontology\":{\"$ref\":\"#/$defs/semantic_ref\"},\"adversarial\":{\"type\":\"boolean\"},\"evidence\":{\"$ref\":\"#/$defs/strings\"},\"meaning\":{\"type\":\"string\",\"minLength\":1}}},"
   "\"evidence_quality\":{\"type\":\"object\",\"required\":[\"id\",\"target\",\"quality\",\"purpose\",\"assessed_by\",\"signals\",\"meaning\"],\"additionalProperties\":false,\"properties\":{\"id\":{\"$ref\":\"#/$defs/semantic_ref\"},\"target\":{\"$ref\":\"#/$defs/path\"},\"quality\":{\"enum\":[\"high\",\"medium\",\"low\"]},\"purpose\":{\"type\":\"string\",\"minLength\":1},\"assessed_by\":{\"$ref\":\"#/$defs/semantic_ref\"},\"signals\":{\"$ref\":\"#/$defs/strings\"},\"meaning\":{\"type\":\"string\",\"minLength\":1}}},"
   "\"verification_lease\":{\"type\":\"object\",\"required\":[\"id\",\"holder\",\"scope\",\"status\",\"authority_effect\",\"evidence\",\"meaning\"],\"additionalProperties\":false,\"properties\":{\"id\":{\"$ref\":\"#/$defs/semantic_ref\"},\"holder\":{\"$ref\":\"#/$defs/semantic_ref\"},\"scope\":{\"type\":\"string\",\"minLength\":1},\"status\":{\"enum\":[\"issued\",\"active\",\"finished\",\"aborted\",\"escalated\"]},\"authority_effect\":{\"enum\":[\"authority-after-checks\",\"authority-blocked\"]},\"evidence\":{\"$ref\":\"#/$defs/strings\"},\"meaning\":{\"type\":\"string\",\"minLength\":1}}},"
   "\"abort_rule\":{\"type\":\"object\",\"required\":[\"id\",\"trigger\",\"effect\",\"meaning\"],\"additionalProperties\":false,\"properties\":{\"id\":{\"$ref\":\"#/$defs/semantic_ref\"},\"trigger\":{\"type\":\"string\",\"minLength\":1},\"effect\":{\"const\":\"authority-blocked\"},\"meaning\":{\"type\":\"string\",\"minLength\":1}}},"
   "\"review_queue\":{\"type\":\"object\",\"required\":[\"id\",\"scope\",\"capacity\",\"assigned\",\"status\",\"freezes\",\"evidence\",\"meaning\"],\"additionalProperties\":false,\"properties\":{\"id\":{\"$ref\":\"#/$defs/semantic_ref\"},\"scope\":{\"type\":\"string\",\"minLength\":1},\"capacity\":{\"type\":\"integer\",\"minimum\":0},\"assigned\":{\"type\":\"integer\",\"minimum\":0},\"status\":{\"enum\":[\"available\",\"near-limit\",\"overloaded\"]},\"freezes\":{\"$ref\":\"#/$defs/strings\"},\"evidence\":{\"$ref\":\"#/$defs/strings\"},\"meaning\":{\"type\":\"string\",\"minLength\":1}}},"
   "\"review_overload\":{\"type\":\"object\",\"required\":[\"id\",\"when\",\"effect\",\"meaning\"],\"additionalProperties\":false,\"properties\":{\"id\":{\"$ref\":\"#/$defs/semantic_ref\"},\"when\":{\"const\":\"overloaded\"},\"effect\":{\"enum\":[\"freeze-governed-automation\",\"create-review-debt\"]},\"meaning\":{\"type\":\"string\",\"minLength\":1}}},"
   "\"feedback_closure\":{\"type\":\"object\",\"required\":[\"id\",\"trigger\",\"update\",\"owner\",\"status\",\"revalidation\",\"evidence\",\"meaning\"],\"additionalProperties\":false,\"properties\":{\"id\":{\"$ref\":\"#/$defs/semantic_ref\"},\"trigger\":{\"type\":\"string\",\"minLength\":1},\"update\":{\"$ref\":\"#/$defs/semantic_ref\"},\"owner\":{\"$ref\":\"#/$defs/semantic_ref\"},\"status\":{\"enum\":[\"open\",\"closed\",\"revalidating\"]},\"revalidation\":{\"type\":\"string\",\"minLength\":1},\"evidence\":{\"$ref\":\"#/$defs/strings\"},\"meaning\":{\"type\":\"string\",\"minLength\":1}}},"
   "\"quarantine_bundle\":{\"type\":\"object\",\"required\":[\"id\",\"subject_kind\",\"status\",\"owner\",\"blocks\",\"evidence\",\"meaning\"],\"additionalProperties\":false,\"properties\":{\"id\":{\"$ref\":\"#/$defs/semantic_ref\"},\"subject_kind\":{\"type\":\"string\",\"minLength\":1},\"status\":{\"enum\":[\"isolated\",\"released\",\"closed\"]},\"owner\":{\"$ref\":\"#/$defs/semantic_ref\"},\"blocks\":{\"$ref\":\"#/$defs/strings\"},\"evidence\":{\"$ref\":\"#/$defs/strings\"},\"meaning\":{\"type\":\"string\",\"minLength\":1}}},"
   "\"confidence_ceiling\":{\"type\":\"object\",\"required\":[\"id\",\"producer\",\"self_confidence\",\"ceiling\",\"decided_by\",\"requires\",\"evidence\",\"meaning\"],\"additionalProperties\":false,\"properties\":{\"id\":{\"$ref\":\"#/$defs/semantic_ref\"},\"producer\":{\"$ref\":\"#/$defs/semantic_ref\"},\"self_confidence\":{\"const\":\"ignored\"},\"ceiling\":{\"enum\":[\"low\",\"medium\",\"high\"]},\"decided_by\":{\"$ref\":\"#/$defs/semantic_ref\"},\"requires\":{\"$ref\":\"#/$defs/strings\"},\"evidence\":{\"$ref\":\"#/$defs/strings\"},\"meaning\":{\"type\":\"string\",\"minLength\":1}}},"
   "\"sidecar_receipt\":{\"type\":\"object\",\"required\":[\"id\",\"producer\",\"output\",\"verifier\",\"independent\",\"evidence\",\"meaning\"],\"additionalProperties\":false,\"properties\":{\"id\":{\"$ref\":\"#/$defs/semantic_ref\"},\"producer\":{\"$ref\":\"#/$defs/semantic_ref\"},\"output\":{\"$ref\":\"#/$defs/path\"},\"verifier\":{\"$ref\":\"#/$defs/semantic_ref\"},\"independent\":{\"const\":true},\"evidence\":{\"$ref\":\"#/$defs/strings\"},\"meaning\":{\"type\":\"string\",\"minLength\":1}}},"
   "\"orchestration_route\":{\"type\":\"object\",\"required\":[\"id\",\"decision\",\"control_plane\",\"agent\",\"policy\",\"authority\",\"evidence\",\"outputs\",\"meaning\"],\"additionalProperties\":false,\"properties\":{\"id\":{\"$ref\":\"#/$defs/semantic_ref\"},\"decision\":{\"$ref\":\"#/$defs/semantic_ref\"},\"control_plane\":{\"$ref\":\"#/$defs/semantic_ref\"},\"agent\":{\"$ref\":\"#/$defs/semantic_ref\"},\"policy\":{\"$ref\":\"#/$defs/semantic_ref\"},\"authority\":{\"$ref\":\"#/$defs/semantic_ref\"},\"evidence\":{\"$ref\":\"#/$defs/strings\"},\"outputs\":{\"$ref\":\"#/$defs/strings\"},\"meaning\":{\"type\":\"string\",\"minLength\":1}}},"
   "\"evidence_change\":{\"type\":\"object\",\"required\":[\"id\",\"change_kind\",\"proposed_by\",\"authority\",\"evidence\",\"debt\",\"meaning\"],\"additionalProperties\":false,\"properties\":{\"id\":{\"$ref\":\"#/$defs/semantic_ref\"},\"change_kind\":{\"enum\":[\"routine\",\"emergency\"]},\"proposed_by\":{\"$ref\":\"#/$defs/semantic_ref\"},\"authority\":{\"$ref\":\"#/$defs/semantic_ref\"},\"evidence\":{\"type\":\"array\",\"items\":{\"$ref\":\"#/$defs/path\"}},\"debt\":{\"type\":\"array\",\"items\":{\"$ref\":\"#/$defs/semantic_ref\"}},\"meaning\":{\"type\":\"string\",\"minLength\":1}}},"))
