(in-package #:dslraid.agent)

(defun verification-manifest-schema-tail-variants-json ()
  (concatenate
   'string
   "{\"type\":\"object\",\"required\":[\"manifest_version\",\"generated_by\",\"subject\",\"source\",\"root_cause_profile\",\"cases\",\"closure_rules\"],\"additionalProperties\":false,\"properties\":{\"manifest_version\":{\"$ref\":\"#/$defs/semver\"},\"generated_by\":{\"const\":\"scripts/verificationrootcausegen.sh\"},\"subject\":{\"$ref\":\"#/$defs/semantic_ref\"},\"source\":{\"$ref\":\"#/$defs/path\"},\"root_cause_profile\":{\"type\":\"string\",\"minLength\":1},\"cases\":{\"type\":\"array\",\"minItems\":1,\"items\":{\"$ref\":\"#/$defs/root_cause_case\"}},\"closure_rules\":{\"type\":\"array\",\"minItems\":1,\"items\":{\"$ref\":\"#/$defs/rule\"}}}},"
   "{\"type\":\"object\",\"required\":[\"manifest_version\",\"generated_by\",\"subject\",\"source\",\"semantic_debugger_profile\",\"sessions\",\"closure_rules\"],\"additionalProperties\":false,\"properties\":{\"manifest_version\":{\"$ref\":\"#/$defs/semver\"},\"generated_by\":{\"const\":\"scripts/verificationdebuggergen.sh\"},\"subject\":{\"$ref\":\"#/$defs/semantic_ref\"},\"source\":{\"$ref\":\"#/$defs/path\"},\"semantic_debugger_profile\":{\"type\":\"string\",\"minLength\":1},\"sessions\":{\"type\":\"array\",\"minItems\":1,\"items\":{\"$ref\":\"#/$defs/semantic_debug_session\"}},\"closure_rules\":{\"type\":\"array\",\"minItems\":1,\"items\":{\"$ref\":\"#/$defs/rule\"}}}},"
   "{\"type\":\"object\",\"required\":[\"manifest_version\",\"generated_by\",\"subject\",\"source\",\"evidence_pruning_profile\",\"decisions\",\"closure_rules\"],\"additionalProperties\":false,\"properties\":{\"manifest_version\":{\"$ref\":\"#/$defs/semver\"},\"generated_by\":{\"const\":\"scripts/verificationpruninggen.sh\"},\"subject\":{\"$ref\":\"#/$defs/semantic_ref\"},\"source\":{\"$ref\":\"#/$defs/path\"},\"evidence_pruning_profile\":{\"type\":\"string\",\"minLength\":1},\"decisions\":{\"type\":\"array\",\"minItems\":1,\"items\":{\"$ref\":\"#/$defs/pruning_decision\"}},\"closure_rules\":{\"type\":\"array\",\"minItems\":1,\"items\":{\"$ref\":\"#/$defs/rule\"}}}},"
   "{\"type\":\"object\",\"required\":[\"manifest_version\",\"generated_by\",\"subject\",\"source\",\"security_audit_profile\",\"boundaries\",\"closure_rules\"],\"additionalProperties\":false,\"properties\":{\"manifest_version\":{\"$ref\":\"#/$defs/semver\"},\"generated_by\":{\"const\":\"scripts/verificationsecuritygen.sh\"},\"subject\":{\"$ref\":\"#/$defs/semantic_ref\"},\"source\":{\"$ref\":\"#/$defs/path\"},\"security_audit_profile\":{\"type\":\"string\",\"minLength\":1},\"boundaries\":{\"type\":\"array\",\"minItems\":1,\"items\":{\"$ref\":\"#/$defs/security_audit_boundary\"}},\"closure_rules\":{\"type\":\"array\",\"minItems\":1,\"items\":{\"$ref\":\"#/$defs/rule\"}}}},"
   "{\"type\":\"object\",\"required\":[\"manifest_version\",\"generated_by\",\"subject\",\"source\",\"failure_profile\",\"conditions\",\"closure_rules\"],\"additionalProperties\":false,\"properties\":{\"manifest_version\":{\"$ref\":\"#/$defs/semver\"},\"generated_by\":{\"const\":\"scripts/verificationfailuregen.sh\"},\"subject\":{\"$ref\":\"#/$defs/semantic_ref\"},\"source\":{\"$ref\":\"#/$defs/path\"},\"failure_profile\":{\"type\":\"string\",\"minLength\":1},\"conditions\":{\"type\":\"array\",\"minItems\":1,\"items\":{\"$ref\":\"#/$defs/failure_condition\"}},\"closure_rules\":{\"type\":\"array\",\"minItems\":1,\"items\":{\"$ref\":\"#/$defs/rule\"}}}},"
   "{\"type\":\"object\",\"required\":[\"manifest_version\",\"generated_by\",\"subject\",\"source\",\"debt_profile\",\"records\",\"closure_rules\"],\"additionalProperties\":false,\"properties\":{\"manifest_version\":{\"$ref\":\"#/$defs/semver\"},\"generated_by\":{\"const\":\"scripts/verificationdebtgen.sh\"},\"subject\":{\"$ref\":\"#/$defs/semantic_ref\"},\"source\":{\"$ref\":\"#/$defs/path\"},\"debt_profile\":{\"type\":\"string\",\"minLength\":1},\"records\":{\"type\":\"array\",\"minItems\":1,\"items\":{\"$ref\":\"#/$defs/debt_record\"}},\"closure_rules\":{\"type\":\"array\",\"minItems\":1,\"items\":{\"$ref\":\"#/$defs/rule\"}}}},"
   "{\"type\":\"object\",\"required\":[\"manifest_version\",\"generated_by\",\"subject\",\"source\",\"access_profile\",\"policies\",\"closure_rules\"],\"additionalProperties\":false,\"properties\":{\"manifest_version\":{\"$ref\":\"#/$defs/semver\"},\"generated_by\":{\"const\":\"scripts/verificationaccessgen.sh\"},\"subject\":{\"$ref\":\"#/$defs/semantic_ref\"},\"source\":{\"$ref\":\"#/$defs/path\"},\"access_profile\":{\"type\":\"string\",\"minLength\":1},\"policies\":{\"type\":\"array\",\"minItems\":1,\"items\":{\"$ref\":\"#/$defs/access_policy\"}},\"closure_rules\":{\"type\":\"array\",\"minItems\":1,\"items\":{\"$ref\":\"#/$defs/rule\"}}}},"
   "{\"type\":\"object\",\"required\":[\"manifest_version\",\"generated_by\",\"subject\",\"source\",\"reliability_profile\",\"records\",\"closure_rules\"],\"additionalProperties\":false,\"properties\":{\"manifest_version\":{\"$ref\":\"#/$defs/semver\"},\"generated_by\":{\"const\":\"scripts/verificationreliabilitygen.sh\"},\"subject\":{\"$ref\":\"#/$defs/semantic_ref\"},\"source\":{\"$ref\":\"#/$defs/path\"},\"reliability_profile\":{\"type\":\"string\",\"minLength\":1},\"records\":{\"type\":\"array\",\"minItems\":1,\"items\":{\"$ref\":\"#/$defs/reliability_record\"}},\"closure_rules\":{\"type\":\"array\",\"minItems\":1,\"items\":{\"$ref\":\"#/$defs/rule\"}}}},"
   "{\"type\":\"object\",\"required\":[\"manifest_version\",\"generated_by\",\"subject\",\"source\",\"agreement_profile\",\"agreements\",\"closure_rules\"],\"additionalProperties\":false,\"properties\":{\"manifest_version\":{\"$ref\":\"#/$defs/semver\"},\"generated_by\":{\"const\":\"scripts/verificationagreementgen.sh\"},\"subject\":{\"$ref\":\"#/$defs/semantic_ref\"},\"source\":{\"$ref\":\"#/$defs/path\"},\"agreement_profile\":{\"type\":\"string\",\"minLength\":1},\"agreements\":{\"type\":\"array\",\"minItems\":1,\"items\":{\"$ref\":\"#/$defs/agreement_record\"}},\"closure_rules\":{\"type\":\"array\",\"minItems\":1,\"items\":{\"$ref\":\"#/$defs/rule\"}}}},"
   "{\"type\":\"object\",\"required\":[\"manifest_version\",\"generated_by\",\"subject\",\"source\",\"control_plane_profile\",\"routes\",\"closure_rules\"],\"additionalProperties\":false,\"properties\":{\"manifest_version\":{\"$ref\":\"#/$defs/semver\"},\"generated_by\":{\"const\":\"scripts/verificationcontrolgen.sh\"},\"subject\":{\"$ref\":\"#/$defs/semantic_ref\"},\"source\":{\"$ref\":\"#/$defs/path\"},\"control_plane_profile\":{\"type\":\"string\",\"minLength\":1},\"routes\":{\"type\":\"array\",\"minItems\":1,\"items\":{\"$ref\":\"#/$defs/control_plane_verification\"}},\"closure_rules\":{\"type\":\"array\",\"minItems\":1,\"items\":{\"$ref\":\"#/$defs/rule\"}}}},"
   "{\"type\":\"object\",\"required\":[\"manifest_version\",\"generated_by\",\"subject\",\"source\",\"provider_compat_profile\",\"records\",\"closure_rules\"],\"additionalProperties\":false,\"properties\":{\"manifest_version\":{\"$ref\":\"#/$defs/semver\"},\"generated_by\":{\"const\":\"scripts/verificationprovidergen.sh\"},\"subject\":{\"$ref\":\"#/$defs/semantic_ref\"},\"source\":{\"$ref\":\"#/$defs/path\"},\"provider_compat_profile\":{\"type\":\"string\",\"minLength\":1},\"records\":{\"type\":\"array\",\"minItems\":1,\"items\":{\"$ref\":\"#/$defs/provider_compat_record\"}},\"closure_rules\":{\"type\":\"array\",\"minItems\":1,\"items\":{\"$ref\":\"#/$defs/rule\"}}}},"
   "{\"type\":\"object\",\"required\":[\"manifest_version\",\"generated_by\",\"subject\",\"source\",\"runtime_trace_profile\",\"mappings\",\"closure_rules\"],\"additionalProperties\":false,\"properties\":{\"manifest_version\":{\"$ref\":\"#/$defs/semver\"},\"generated_by\":{\"const\":\"scripts/verificationruntimegen.sh\"},\"subject\":{\"$ref\":\"#/$defs/semantic_ref\"},\"source\":{\"$ref\":\"#/$defs/path\"},\"runtime_trace_profile\":{\"type\":\"string\",\"minLength\":1},\"mappings\":{\"type\":\"array\",\"minItems\":1,\"items\":{\"$ref\":\"#/$defs/runtime_trace_mapping\"}},\"closure_rules\":{\"type\":\"array\",\"minItems\":1,\"items\":{\"$ref\":\"#/$defs/rule\"}}}}"))
