(in-package #:dslraid.emit)

(defparameter *backend-targets*
  '(("rust" "generated runtime source" "Canonical IR" "no"
     "Rust can be runtime code or generated output; Lisp forms stay SSOT.")
    ("go" "generated runtime source" "Canonical IR" "no"
     "Go output follows the same modeled FSM behavior contract.")
    ("typescript" "viewer/runtime adapter source" "Canonical IR" "no"
     "TypeScript output is derived tooling surface, not authoring truth.")
    ("mermaid" "documentation diagram" "Canonical IR" "yes"
     "Mermaid export is for readable docs and may omit executable detail.")
    ("dot" "dense graph layout input" "Canonical IR" "yes"
     "DOT export is for layout/debugging and may omit architecture metadata.")
    ("svg" "static visualization" "ViewModel" "yes"
     "SVG renders a projection snapshot, not the full IR.")
    ("markdown" "generated documentation" "Canonical IR" "partial"
     "Docs explain derived structure while preserving traceable subjects.")))

(defun emit-backend-targets-markdown (&optional stream)
  "Emit deterministic Markdown for Canonical IR backend targets."
  (let ((markdown (with-output-to-string (out)
                    (write-backend-targets-doc out))))
    (if stream
        (write-string markdown stream)
        markdown)))

(defun write-backend-targets-doc (out)
  (format out "# DSLRaid Backend Targets~%~%")
  (format out "<!-- generated by scripts/backendgen.sh; do not edit by hand -->~%~%")
  (format out "Backends consume Canonical IR or projection products.~%")
  (format out "Common Lisp forms remain the native authoring SSOT.~%~%")
  (write-backend-target-table out))

(defun write-backend-target-table (out)
  (format out "| Target | Role | Input | Lossy | Contract |~%")
  (format out "| --- | --- | --- | --- | --- |~%")
  (dolist (target *backend-targets*)
    (destructuring-bind (id role input lossy contract) target
      (format out "| ~A | ~A | ~A | ~A | ~A |~%"
              id role input lossy contract))))
