(in-package #:dslraid.emit)

(defun emit-language-diagnostics-markdown (&optional stream)
  "Emit deterministic Markdown for Lisp language diagnostics."
  (let ((markdown (with-output-to-string (out)
                    (write-language-diagnostics-doc out))))
    (if stream
        (write-string markdown stream)
        markdown)))

(defun write-language-diagnostics-doc (out)
  (format out "# DSLRaid Lisp Language Diagnostics~%~%")
  (format out "<!-- generated by scripts/langdiaggen.sh; do not edit by hand -->~%~%")
  (format out "Source: `lisp/lang/codes.lisp`~%~%")
  (format out "| Code | Severity | Scope | Summary |~%")
  (format out "| --- | --- | --- | --- |~%")
  (dolist (entry (dslraid.lang::language-diagnostic-catalog))
    (format out "| ~A | ~A | ~A | ~A |~%"
            (getf entry :code)
            (getf entry :severity)
            (getf entry :scope)
            (getf entry :summary))))
