(in-package #:dslraid.emit)
(defparameter *default-projections*
  '(("view:runtime" "fsm:runtime")
    ("view:agent" "fsm:agent")
    ("view:workspace" "fsm:workspace")))

(defun write-derived-project-sections (out)
  (write-runtime-context out)
  (write-projections out)
  (write-codegen-derivation out)
  (write-codegen-artifacts out)
  (indent out 1)
  (format out "\"diagnostics\": []~%"))

(defun write-runtime-context (out)
  (indent out 1)
  (format out "\"contexts\": [~%")
  (indent out 2)
  (format out "{")
  (format out "\"id\": \"context:runtime\", \"name\": \"Runtime Context\", ")
  (format out "\"kind\": \"bounded_context\", ")
  (format out "\"owns\": [\"fsm:runtime\", \"fsm:agent\", \"fsm:workspace\"]")
  (format out "}~%")
  (indent out 1)
  (format out "],~%"))

(defun write-projections (out)
  (indent out 1)
  (format out "\"projections\": [~%")
  (loop for item in *default-projections*
        for last = (eq item (car (last *default-projections*)))
        do (write-projection out item last))
  (indent out 1)
  (format out "],~%"))

(defun write-projection (out item last)
  (destructuring-bind (id source) item
    (indent out 2)
    (format out "{")
    (format out "\"id\": ~A, \"kind\": \"projection\", "
            (json-string id))
    (format out "\"source\": ~A, " (json-string source))
    (format out "\"show\": [\"states\", \"transitions\", \"events\", \"artifacts\"]")
    (format out "}~:[,~;~]~%" last)))

(defun write-codegen-derivation (out)
  (indent out 1)
  (format out "\"derivations\": [~%")
  (indent out 2)
  (format out "{\"id\": \"derivation:lisp_runtime_codegen\", ")
  (format out "\"source\": \"context:runtime\", ")
  (format out "\"rule\": {")
  (format out "\"id\": \"fsm_codegen\", \"kind\": \"codegen\", ")
  (format out "\"generator\": \"dslraid-codegen\", \"version\": \"0.1.0\"")
  (format out "}, ")
  (format out "\"targets\": [")
  (format out "{\"artifact\": \"artifact:runtime_fsm.rs\", \"role\": \"generated\"}")
  (format out "]")
  (format out "}~%")
  (indent out 1)
  (format out "],~%"))

(defun write-codegen-artifacts (out)
  (indent out 1)
  (format out "\"artifacts\": [~%")
  (indent out 2)
  (format out "{\"id\": \"artifact:runtime_fsm.rs\", ")
  (format out "\"kind\": \"generated\", ")
  (format out "\"path\": \"generated/runtime_fsm.rs\", ")
  (format out "\"generated_by\": \"derivation:lisp_runtime_codegen\", ")
  (format out "\"visibility\": \"public\", ")
  (format out "\"tags\": [\"generated\", \"rust\", \"lisp-ssot\"]")
  (format out "}~%")
  (indent out 1)
  (format out "],~%"))
