(in-package #:dslraid.emit)

(defun write-fsm-json (fsm out level)
  (indent out level)
  (format out "{~%")
  (json-field out (1+ level) "id" (fsm-id fsm) t)
  (json-field out (1+ level) "name" (fsm-name fsm) t)
  (when (fsm-defined-at fsm)
    (indent out (1+ level))
    (format out "\"defined_at\": ")
    (write-defined-at-json (fsm-defined-at fsm) out)
    (format out ",~%"))
  (write-named-array out level "states" (fsm-states fsm) #'write-state-json t)
  (write-named-array out level "events" (fsm-events fsm) #'write-event-json t)
  (write-named-array out level "guards" (fsm-guards fsm) #'write-guard-json t)
  (write-named-array out level "actions" (fsm-actions fsm) #'write-action-json t)
  (write-named-array out level "transitions" (fsm-transitions fsm) #'write-transition-json nil)
  (indent out level)
  (format out "}"))

(defun write-named-array (out level name items writer comma-p)
  (indent out (1+ level))
  (format out "\"~A\": [~%" name)
  (write-json-array items out (+ level 2) writer)
  (when comma-p (format out ","))
  (format out "~%"))
