(in-package #:dslraid.emit)

(defun write-derived-project-sections (out)
  (write-runtime-context out)
  (write-compositions out)
  (write-projections out)
  (write-codegen-derivation out)
  (write-codegen-artifacts out)
  (indent out 1)
  (format out "\"diagnostics\": []~%"))

(defun write-codegen-derivation (out)
  (indent out 1)
  (format out "\"derivations\": [~%")
  (indent out 2)
  (format out "{\"id\": \"derivation:lisp_runtime_codegen\", ")
  (format out "\"source\": \"context:runtime\", ")
  (format out "\"rule\": {")
  (format out "\"id\": \"fsm_codegen\", \"kind\": \"codegen\", ")
  (format out "\"generator\": \"dslraid-codegen\", \"version\": \"0.1.0\"")
  (format out "}, ")
  (format out "\"targets\": [")
  (format out "{\"artifact\": \"artifact:runtime_fsm.rs\", \"role\": \"generated\"}")
  (format out "]")
  (format out "}~%")
  (indent out 1)
  (format out "],~%"))

(defun write-codegen-artifacts (out)
  (indent out 1)
  (format out "\"artifacts\": [~%")
  (indent out 2)
  (format out "{\"id\": \"artifact:runtime_fsm.rs\", ")
  (format out "\"kind\": \"generated\", ")
  (format out "\"path\": \"generated/runtime_fsm.rs\", ")
  (format out "\"generated_by\": \"derivation:lisp_runtime_codegen\", ")
  (format out "\"visibility\": \"public\", ")
  (format out "\"tags\": [\"generated\", \"rust\", \"lisp-ssot\"]")
  (format out "}~%")
  (indent out 1)
  (format out "],~%"))
