(in-package #:dslraid.emit)

(defun write-fsm-json (fsm out level)
  (indent out level)
  (format out "{~%")
  (json-field out (1+ level) "id" (fsm-id fsm) t)
  (json-field out (1+ level) "name" (fsm-name fsm) t)
  (when (fsm-defined-at fsm)
    (indent out (1+ level))
    (format out "\"defined_at\": ")
    (write-defined-at-json (fsm-defined-at fsm) out)
    (format out ",~%"))
  (write-named-array out level "states" (fsm-states fsm) #'write-state-json t)
  (write-named-array out level "events" (fsm-events fsm) #'write-event-json t)
  (write-named-array out level "guards" (fsm-guards fsm) #'write-guard-json t)
  (write-named-array out level "actions" (fsm-actions fsm) #'write-action-json t)
  (write-named-array out level "transitions" (fsm-transitions fsm) #'write-transition-json nil)
  (indent out level)
  (format out "}"))

(defun write-named-array (out level name items writer comma-p)
  (indent out (1+ level))
  (format out "\"~A\": [~%" name)
  (write-json-array items out (+ level 2) writer)
  (when comma-p (format out ","))
  (format out "~%"))

(defun write-state-json (state out level)
  (indent out level)
  (format out "{")
  (format out "\"id\": ~A, \"kind\": ~A"
          (json-string (state-id state))
          (json-string (state-kind state)))
  (when (state-initial-p state)
    (format out ", \"initial\": true"))
  (when (state-terminal-p state)
    (format out ", \"terminal\": true"))
  (when (state-terminal-semantics state)
    (format out ", \"terminal_semantics\": ~A"
            (json-string (state-terminal-semantics state))))
  (write-defined-at-property (state-defined-at state) out)
  (format out "}"))

(defun write-event-json (event out level)
  (indent out level)
  (format out "{\"id\": ~A, \"kind\": ~A}"
          (json-string (event-id event))
          (json-string (event-kind event))))

(defun write-transition-json (transition out level)
  (indent out level)
  (format out "{")
  (format out "\"id\": ~A, \"from\": ~A, \"to\": ~A"
          (json-string (transition-id transition))
          (json-string (transition-from transition))
          (json-string (transition-to transition)))
  (write-optional-transition-fields transition out)
  (write-defined-at-property (transition-defined-at transition) out)
  (format out "}"))

(defun write-optional-transition-fields (transition out)
  (when (transition-on transition)
    (format out ", \"on\": ~A" (json-string (transition-on transition))))
  (when (transition-guards transition)
    (format out ", \"guards\": ~A" (json-string-array (transition-guards transition))))
  (when (transition-actions transition)
    (format out ", \"actions\": ~A" (json-string-array (transition-actions transition))))
  (when (transition-requires transition)
    (format out ", \"requires\": ~A" (json-string-array (transition-requires transition)))))
