(in-package #:dslraid.emit)

(defparameter *language-pipeline*
  '(("Lisp forms" "Native authoring SSOT and executable ontology surface.")
    ("Reader" "Common Lisp reads forms without turning Lisp into plain text.")
    ("Macro expansion" "Surface syntax expands into ordinary authoring data.")
    ("Language AST" "Authoring forms keep source-level diagnostic context.")
    ("Language conformance" "Duplicate states, events, and transitions fail early.")
    ("Canonical IR" "Stable interchange data consumed by Rust runtime tooling.")
    ("IR conformance" "Cross-language semantic contract and diagnostics.")
    ("Projection" "View models, docs, traces, and backend outputs derive here.")
    ("Backend output" "Rust, Go, TypeScript, Mermaid, DOT, SVG, and docs.")))

(defparameter *language-contracts*
  '("Lisp forms are the native source of truth."
    "Authoring order is preserved as deterministic semantic presentation order."
    "Macros must not hide IO, conformance, projection, or backend codegen."
    "Backends consume Canonical IR, not raw Lisp forms."
    "Rust source can be generated runtime output, not authoring truth."
    "Generated language docs are checked by lisp-docgen."
    "Generated Lisp Canonical IR is checked by lisp-irgen and Rust validation."
    "Generated Rust backend code is checked by lisp-rustgen."))

(defun emit-language-pipeline-markdown (&optional stream)
  "Emit deterministic Markdown for the Lisp authoring pipeline."
  (let ((markdown (with-output-to-string (out)
                    (write-language-doc out))))
    (if stream
        (write-string markdown stream)
        markdown)))

(defun write-language-doc (out)
  (format out "# DSLRaid Lisp Pipeline~%~%")
  (format out "<!-- generated by scripts/lisp-docgen.sh; do not edit by hand -->~%~%")
  (format out "The Common Lisp layer is DSLRaid's native authoring surface.~%")
  (format out "It expands executable forms into Canonical IR before Rust tooling runs.~%~%")
  (write-stage-table out)
  (write-contracts out)
  (write-command out))

(defun write-stage-table (out)
  (format out "## Pipeline~%~%")
  (format out "| Stage | Contract |~%| --- | --- |~%")
  (dolist (stage *language-pipeline*)
    (format out "| ~A | ~A |~%" (first stage) (second stage)))
  (terpri out))

(defun write-contracts (out)
  (format out "## Contracts~%~%")
  (dolist (contract *language-contracts*)
    (format out "- ~A~%" contract))
  (terpri out))

(defun write-command (out)
  (format out "## Regeneration~%~%")
  (format out "```bash~%")
  (format out "bash scripts/lisp-docgen.sh generate~%")
  (format out "bash scripts/lisp-docgen.sh check~%")
  (format out "bash scripts/lisp-irgen.sh generate~%")
  (format out "bash scripts/lisp-irgen.sh check~%")
  (format out "bash scripts/lisp-rustgen.sh check~%")
  (format out "```~%"))
