# generated by scripts/makegen.sh; do not edit by hand
.PHONY: verify-daemon lint unit-test integration-test conformance release-check

verify-daemon: release-check

lint:
	go install github.com/rhysd/actionlint/cmd/actionlint@v1.7.12
	actionlint_bin="$$(go env GOPATH)/bin/actionlint" && "$$actionlint_bin"
	bash scripts/check-source-lines.sh
	bash scripts/go-lint.sh
	cargo fmt --all -- --check
	cargo clippy --workspace --all-targets -- -D warnings

unit-test: lint
	cargo test --workspace

integration-test: unit-test
	npm --prefix apps/viewer ci
	npm --prefix apps/viewer test
	npm --prefix apps/viewer run build

conformance: integration-test
	cargo run -p dslraid-cli -- quality

release-check: conformance
	bash scripts/releasecheckgen.sh check
	bash scripts/releasecheck/core.sh
	bash scripts/releasecheck/governance.sh
	bash scripts/releasecheck/runtime.sh
	bash scripts/releasecheck/ssot.sh
	bash scripts/releasecheck/artifacts.sh
