import type { Artifact, CoreIr, InspectorPanel } from "../../types";

export function artifactPanel(ir: CoreIr, artifact: Artifact): InspectorPanel {
  const derivation = artifact.generated_by
    ? (ir.derivations ?? []).find((item) => item.id === artifact.generated_by)
    : undefined;
  return {
    subject: artifact.id,
    title: artifact.path,
    sections: [
      {
        title: "Artifact",
        rows: [
          { label: "Kind", value: artifact.kind },
          { label: "Path", value: artifact.path },
          { label: "Visibility", value: artifact.visibility ?? "unspecified" },
          { label: "Tags", value: (artifact.tags ?? []).join(", ") || "none" }
        ]
      },
      {
        title: "Derivation",
        rows: derivationRows(artifact, derivation?.source)
      }
    ]
  };
}

function derivationRows(artifact: Artifact, source: string | undefined) {
  if (!artifact.generated_by) {
    return [{ label: "Generated By", value: "not generated" }];
  }
  return [
    { label: "Generated By", value: artifact.generated_by, subject: artifact.generated_by },
    { label: "Source", value: source ?? "unknown", subject: source }
  ];
}
