use anyhow::{bail, Context, Result};
use clap::CommandFactory;
use std::fs;
use std::path::Path;

pub(super) fn run(command: crate::CliDocCommand) -> Result<()> {
    match command {
        crate::CliDocCommand::Generate { out } => generate(out.as_deref()),
        crate::CliDocCommand::Check { golden } => check(&golden),
    }
}

fn generate(out: Option<&Path>) -> Result<()> {
    let markdown = render();
    crate::write_or_stdout(out, markdown.as_bytes())
}

fn check(golden: &Path) -> Result<()> {
    let actual = render();
    let expected = fs::read_to_string(golden)
        .with_context(|| format!("read CLI reference {}", golden.display()))?;
    if actual != expected {
        bail!(
            "CLI reference is stale: run `dslraid doc cli generate --out {}`",
            golden.display()
        );
    }
    Ok(())
}

fn render() -> String {
    let mut out = String::new();
    out.push_str("# DSLRaid CLI Reference\n\n");
    out.push_str("<!-- generated by dslraid doc cli generate; do not edit by hand -->\n\n");
    super::cli_walk::push_command(&mut out, crate::Cli::command(), "dslraid".to_string());
    out
}
