package repolink

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

type Document struct {
	SchemaVersion string    `json:"schema_version"`
	ID            string    `json:"id"`
	Title         string    `json:"title"`
	Output        string    `json:"output"`
	Summary       string    `json:"summary"`
	Sections      []Section `json:"sections"`
}

type Section struct {
	Heading      string   `json:"heading"`
	Paragraphs   []string `json:"paragraphs,omitempty"`
	Bullets      []string `json:"bullets,omitempty"`
	CodeLanguage string   `json:"code_language,omitempty"`
	Code         string   `json:"code,omitempty"`
}

func GenerateDocuments(root string) error {
	doc, err := loadDocument(root)
	if err != nil {
		return err
	}
	output := filepath.Join(root, filepath.FromSlash(doc.Output))
	if err := os.MkdirAll(filepath.Dir(output), 0o755); err != nil {
		return err
	}
	return os.WriteFile(output, renderDocument(doc), 0o644)
}

func CheckDocuments(root string) error {
	doc, err := loadDocument(root)
	if err != nil {
		return err
	}
	body, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(doc.Output)))
	if err != nil {
		return err
	}
	if !bytes.Equal(body, renderDocument(doc)) {
		return fmt.Errorf("generated document is stale: %s", doc.Output)
	}
	return nil
}

func loadDocument(root string) (Document, error) {
	path := filepath.Join(root, "docs-src", "document-code-coupling.json")
	file, err := os.Open(path)
	if err != nil {
		return Document{}, err
	}
	defer file.Close()
	var doc Document
	decoder := json.NewDecoder(file)
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&doc); err != nil {
		return Document{}, err
	}
	var extra any
	if err := decoder.Decode(&extra); !errors.Is(err, io.EOF) {
		return Document{}, errors.New("document source must contain one JSON value")
	}
	if doc.SchemaVersion != "repo.document/v1" || doc.ID == "" || doc.Title == "" || doc.Summary == "" || len(doc.Sections) == 0 {
		return Document{}, errors.New("document source is incomplete")
	}
	if filepath.IsAbs(doc.Output) || filepath.Clean(doc.Output) != doc.Output || strings.HasPrefix(doc.Output, "..") || !strings.HasSuffix(doc.Output, ".md") {
		return Document{}, errors.New("document output is unsafe")
	}
	return doc, nil
}

func renderDocument(doc Document) []byte {
	var out bytes.Buffer
	fmt.Fprintf(&out, "# %s\n\n<!-- generated by go run ./cmd/repoctl docs generate; do not edit by hand -->\n\n%s\n", doc.Title, doc.Summary)
	for _, section := range doc.Sections {
		fmt.Fprintf(&out, "\n## %s\n", section.Heading)
		for _, paragraph := range section.Paragraphs {
			fmt.Fprintf(&out, "\n%s\n", paragraph)
		}
		if len(section.Bullets) > 0 {
			out.WriteByte('\n')
			for _, item := range section.Bullets {
				fmt.Fprintf(&out, "- %s\n", item)
			}
		}
		if section.Code != "" {
			fmt.Fprintf(&out, "\n```%s\n%s\n```\n", section.CodeLanguage, strings.TrimSuffix(section.Code, "\n"))
		}
	}
	return out.Bytes()
}
