import assert from "node:assert/strict";
import { test } from "node:test";
import { loadTs } from "./helpers/load-ts.mjs";

test("artifactPanel links generated Rust output back to derivation and source", async () => {
  const { artifactPanel } = await loadTs("src/graph/inspector/artifact-panel.ts");
  const panel = artifactPanel(fixtureIr(), fixtureArtifact());
  const artifactRows = rows(panel.sections[0]);
  const derivationRows = rows(panel.sections[1]);

  assert.equal(panel.subject, "artifact:runtime_fsm.rs");
  assert.equal(artifactRows.Kind.value, "generated");
  assert.equal(artifactRows.Path.value, "generated/runtime_fsm.rs");
  assert.equal(derivationRows["Generated By"].subject, "derivation:runtime.codegen");
  assert.equal(derivationRows.Source.subject, "fsm:runtime");
});

test("derivationPanel exposes source and generated targets", async () => {
  const { derivationPanel } = await loadTs("src/graph/inspector/derivation-panel.ts");
  const panel = derivationPanel(fixtureIr().derivations[0]);
  const derivationRows = rows(panel.sections[0]);
  const targetRows = panel.sections[1].rows;

  assert.equal(derivationRows.Source.subject, "fsm:runtime");
  assert.equal(derivationRows.Generator.value, "dslraid-codegen");
  assert.equal(targetRows[0].subject, "artifact:runtime_fsm.rs");
});

function rows(section) {
  return Object.fromEntries(section.rows.map((row) => [row.label, row]));
}

function fixtureArtifact() {
  return fixtureIr().artifacts[0];
}

function fixtureIr() {
  return {
    derivations: [
      {
        id: "derivation:runtime.codegen",
        source: "fsm:runtime",
        rule: { id: "fsm_codegen", kind: "codegen", generator: "dslraid-codegen" },
        targets: [{ artifact: "artifact:runtime_fsm.rs", role: "generated" }]
      }
    ],
    artifacts: [
      {
        id: "artifact:runtime_fsm.rs",
        kind: "generated",
        path: "generated/runtime_fsm.rs",
        generated_by: "derivation:runtime.codegen"
      }
    ]
  };
}
