import glob
import json
import os
import sys

from actions_suite_policy import expected_workflows, forbidden_tokens

data = json.load(open(sys.argv[1], encoding="utf-8"))
errors = []
seen_ids = set()
seen_workflows = set()

def add(message):
    errors.append(message)

def check_unique(row):
    for field, seen in (("id", seen_ids), ("workflow", seen_workflows)):
        value = row[field]
        if value in seen:
            add(f"duplicate {field} {value}")
        seen.add(value)


def check_text(row, text):
    if "permissions:" not in text:
        add(f"{row['id']} missing permissions block")
    if "concurrency:" not in text:
        add(f"{row['id']} missing concurrency block")
    for item in forbidden_tokens:
        if item in text:
            add(f"{row['id']} uses forbidden token {item}")
    if "contents: write" in text and row["workflow"] != ".github/workflows/release.yml":
        add(f"{row['id']} has non-release contents write")


def check_generated(row, text):
    if not row.get("generated"):
        return
    header = f"# generated by {row['generator']}"
    if not any(header in line for line in text.splitlines()[:3]):
        add(f"{row['id']} missing generated header")
    if not os.path.exists(row["generator"]):
        add(f"{row['id']} missing generator")


def check_row(row):
    check_unique(row)
    if not os.path.exists(row["workflow"]):
        add(f"missing workflow {row['workflow']}")
        return
    text = open(row["workflow"], encoding="utf-8").read()
    check_text(row, text)
    check_generated(row, text)
    for item in row.get("permissions", []):
        if item not in text:
            add(f"{row['id']} missing permission {item}")
    for item in row.get("evidence", []):
        if not os.path.exists(item):
            add(f"{row['id']} missing evidence {item}")


for row in data.get("workflows", []):
    check_row(row)

actual = set(glob.glob(".github/workflows/*.yml"))
actual.update(glob.glob(".github/workflows/*.yaml"))
if seen_workflows != expected_workflows or actual != expected_workflows:
    add(f"workflow suite mismatch: missing={sorted(expected_workflows - seen_workflows)}")
    add(f"workflow suite mismatch: extra={sorted(actual - expected_workflows)}")
if not data.get("closure_rules"):
    add("github actions suite manifest has no rules")
if errors:
    print("\n".join(errors), file=sys.stderr)
    sys.exit(1)
print("verification GitHub Actions suite check ok")
