import json
import sys

def cell(value):
    return str(value).replace("|", "\\|").replace("\n", " ")


def count_quality_snapshots(manifest):
    return sum(len(e.get("quality_snapshots", [])) for e in manifest.get("evidence", []))

def debt_counts(manifest):
    debts = manifest.get("debts", [])
    revalidation_dates = sum(1 for debt in debts if "revalidate_at" in debt)
    closure_updates = sum(len(debt.get("updates", [])) for debt in debts)
    return debts, closure_updates, revalidation_dates


def loss_counts(manifest):
    translations = manifest.get("translations", [])
    losses = [loss for item in translations for loss in item.get("losses", [])]
    forbidden = sum(1 for loss in losses if loss.get("level") == "L4" or loss.get("status") == "forbidden")
    return translations, losses, forbidden

def print_header(run, ssot):
    print("# DSLRaid Agent Run Manifest\n")
    print("<!-- generated by scripts/agentmanifestgen.sh; do not edit by hand -->\n")
    print(f"Run: `{cell(run['id'])}`")
    print(f"SSOT: `{cell(ssot['context'])}` / ontology `{cell(ssot['ontology_version'])}`\n")


def print_table(rows):
    print("| Surface | Status | Evidence |")
    print("| --- | --- | --- |")
    for name, status, evidence in rows:
        print(f"| {name} | {status} | {evidence} |")

def manifest_rows(manifest):
    gate = manifest["authority_gate"]
    lease = manifest["lease"]
    ssot = manifest["ssot"]
    capacity = manifest.get("review_capacity", {})
    orchestration = manifest.get("orchestration", {})
    debts, closure_updates, revalidation_dates = debt_counts(manifest)
    translations, losses, forbidden_losses = loss_counts(manifest)
    claims = manifest.get("claims", [])
    high_claims = sum(1 for claim in claims if claim.get("confidence") == "high")
    return [
        ("authority gate", f"{cell(gate['decision'])} / {cell(gate.get('profile', 'missing'))}", f"scope `{cell(gate.get('scope', ''))}`, policy `{cell(gate['policy_hash'])}`"),
        ("review capacity", cell(capacity.get("status", "missing")), f"queue `{cell(capacity.get('queue_depth', ''))}/{cell(capacity.get('max_queue_depth', ''))}`"),
        ("orchestration", cell(orchestration.get("id", "missing")), f"route `{cell(orchestration.get('routed_by', ''))}`, verifier `{cell(orchestration.get('verified_by', ''))}`"),
        ("ssot revalidation", cell(ssot.get("revalidation", {}).get("status", "missing")), f"`{cell(ssot.get('revalidation', {}).get('revalidate_at', ''))}`"),
        ("lease", cell(lease["status"]), f"`{cell(lease['id'])}`"),
        ("producer", cell(manifest["producer"]["id"]), f"{cell(manifest['producer']['reasoning_level'])} / {cell(manifest['producer'].get('trust_tier', ''))}"),
        ("reviewers", len(manifest.get("reviewers", [])), "independent sidecars"),
        ("agreements", len(manifest.get("agreements", [])), "cross-agent receipts"),
        ("semantic diffs", len(manifest.get("semantic_diffs", [])), "meaning-level receipts"),
        ("evidence", len(manifest.get("evidence", [])), "linked records"),
        ("evidence quality", count_quality_snapshots(manifest), "sidecar snapshots"),
        ("artifacts", len(manifest.get("artifacts", [])), "generated outputs"),
        ("claims", len(claims), f"high confidence `{high_claims}`"),
        ("containments", len(manifest.get("containments", [])), "abort/quarantine bundles"),
        ("translations", len(translations), "context handoffs"),
        ("loss ledger", len(losses), f"forbidden `{forbidden_losses}`"),
        ("debts", len(debts), f"closure updates `{closure_updates}`, revalidation `{revalidation_dates}`"),
        ("semantic gate", "checked", "`dslraid quality`"),
    ]

manifest = json.load(open(sys.argv[1]))
print_header(manifest["run"], manifest["ssot"])
print_table(manifest_rows(manifest))
