import sys

doc = open(sys.argv[1], encoding="utf-8").read()
errors = []

required_principles = [
    "evidence-before-change",
    "versioned-ssot",
    "bounded-context",
    "context-map",
    "loss-ledger",
    "evidence-graph",
    "evidence-quality",
    "debt-register",
    "incompleteness-ledger",
    "feedback-closure",
    "executable-knowledge",
    "semantic-diff",
    "verification-sidecar",
    "governed-compiler-farm",
    "reasoning-access",
    "access-policy",
    "knowledge-conversion",
]

required_phrases = [
    "Agent outputs are executable claims to verify",
    "Failures must become evidence",
    "Common Lisp forms are the executable knowledge surface.",
    "Canonical IR is the interchange product for Rust tooling.",
    "CI and sidecars produce evidence",
]


def require(condition, message):
    if not condition:
        errors.append(message)


for principle in required_principles:
    require(f"| {principle} |" in doc, f"missing principle {principle}")

for phrase in required_phrases:
    require(phrase in doc, f"missing phrase {phrase!r}")

require("Source: `lisp/agent/principles.lisp`" in doc, "missing Lisp SSOT source")
require("<!-- generated by scripts/agentprinciplegen.sh" in doc, "missing generated marker")
require("## Bootloader Contract" in doc, "missing bootloader contract")

if errors:
    print("\n".join(errors), file=sys.stderr)
    sys.exit(1)

print("agent principle coverage check ok")
