release_workflow = ".github/workflows/release.yml"

expected_gates = {
    "release-provenance:tag-trigger",
    "release-provenance:generated-check",
    "release-provenance:build-test",
    "release-provenance:publish-permission",
    "release-provenance:create-release",
}

workflow_tokens = [
    "# generated by scripts/releasegen.sh",
    "workflow_dispatch:",
    "tags:",
    "- 'v*'",
    "permissions:",
    "contents: write",
    "concurrency:",
    "GH_TOKEN",
    "gh release create",
]
