#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$script_dir/lib/generated.sh"

dslraid_enter_repo

mode="${1:-check}"
input="${2:-examples/runscope/runscope.agent-run.json}"
out="${3:-docs/generated/agent-run-manifest.md}"

generate() {
  python3 - "$repo/$input" <<'PY'
import json
import sys

manifest = json.load(open(sys.argv[1]))
run = manifest["run"]
gate = manifest["authority_gate"]
lease = manifest["lease"]
ssot = manifest["ssot"]
ssot_revalidation = ssot.get("revalidation", {})
quality_snapshots = sum(
    len(evidence.get("quality_snapshots", []))
    for evidence in manifest.get("evidence", [])
)
revalidation_dates = sum(
    1 for debt in manifest.get("debts", [])
    if "revalidate_at" in debt
)
translations = manifest.get("translations", [])
losses = [loss for item in translations for loss in item.get("losses", [])]
forbidden_losses = sum(
    1 for loss in losses
    if loss.get("level") == "L4" or loss.get("status") == "forbidden"
)

def cell(value):
    return str(value).replace("|", "\\|").replace("\n", " ")

print("# DSLRaid Agent Run Manifest\n")
print("<!-- generated by scripts/agentmanifestgen.sh; do not edit by hand -->\n")
print(f"Run: `{cell(run['id'])}`")
print(f"SSOT: `{cell(ssot['context'])}` / ontology `{cell(ssot['ontology_version'])}`\n")
print("| Surface | Status | Evidence |")
print("| --- | --- | --- |")
print(f"| authority gate | {cell(gate['decision'])} | policy `{cell(gate['policy_hash'])}` |")
print(f"| ssot revalidation | {cell(ssot_revalidation.get('status', 'missing'))} | `{cell(ssot_revalidation.get('revalidate_at', ''))}` |")
print(f"| lease | {cell(lease['status'])} | `{cell(lease['id'])}` |")
print(f"| producer | {cell(manifest['producer']['id'])} | {cell(manifest['producer']['reasoning_level'])} / {cell(manifest['producer'].get('trust_tier', ''))} |")
print(f"| reviewers | {len(manifest.get('reviewers', []))} | independent sidecars |")
print(f"| evidence | {len(manifest.get('evidence', []))} | linked records |")
print(f"| evidence quality | {quality_snapshots} | sidecar snapshots |")
print(f"| artifacts | {len(manifest.get('artifacts', []))} | generated outputs |")
print(f"| translations | {len(translations)} | context handoffs |")
print(f"| loss ledger | {len(losses)} | forbidden `{forbidden_losses}` |")
print(f"| debts | {len(manifest.get('debts', []))} | tracked open work |")
print(f"| debt revalidation | {revalidation_dates} | authority dates |")
print("| semantic gate | checked | `dslraid quality` |")
PY
}

dslraid_generated_case \
  "$mode" "$out" \
  "generated agent run manifest is stale: run scripts/agentmanifestgen.sh generate" \
  "agent run manifest generated doc ok" \
  "usage: scripts/agentmanifestgen.sh [generate|check] [input] [out]"
