#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$script_dir/lib/generated.sh"

mode="${1:-check}"
registry="${2:-examples/runscope/runscope.assertions.json}"
report="${3:-examples/runscope/runscope.validation.json}"
out="${4:-docs/generated/assertion-catalog.md}"

generate() {
  python3 - "$repo/$registry" "$repo/$report" <<'PY'
import json
import sys
from collections import Counter, defaultdict

registry_path, report_path = sys.argv[1:3]
registry = json.load(open(registry_path))
report = json.load(open(report_path))
counts = defaultdict(Counter)
for item in report.get("assertions", []):
    counts[item["id"]][item.get("status", "unknown")] += 1

def format_counts(counter):
    if not counter:
        return "not-run"
    return ", ".join(f"{key}:{counter[key]}" for key in sorted(counter))

def cell(value):
    return str(value).replace("|", "\\|").replace("\n", " ")

print("# DSLRaid Assertion Catalog\n")
print("<!-- generated by scripts/assertiongen.sh; do not edit by hand -->\n")
print(f"Registry version: {registry['assertion_version']}")
print(f"Validation source: {report['source']['core_ir']}\n")
print("| Assertion | Proposition | Code | Layer | Severity | Scope | Predicate | Result |")
print("| --- | --- | --- | --- | --- | --- | --- | --- |")
for item in sorted(registry["assertions"], key=lambda value: value["id"]):
    result = format_counts(counts[item["id"]])
    row = [item[key] for key in (
        "id", "proposition", "code", "layer", "severity", "scope", "predicate")]
    row.append(result)
    print("| " + " | ".join(cell(value) for value in row) + " |")
PY
}

dslraid_enter_repo
dslraid_generated_case \
  "$mode" "$out" \
  "generated assertion catalog is stale: run scripts/assertiongen.sh generate" \
  "assertion generated doc ok" \
  "usage: scripts/assertiongen.sh [generate|check] [registry] [report] [out]"
