#!/usr/bin/env bash
set -euo pipefail

repo="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
mode="${1:-check}"
registry="${2:-examples/runscope/runscope.assertions.json}"
report="${3:-examples/runscope/runscope.validation.json}"
out="${4:-docs/generated/assertion-catalog.md}"
target="$repo/$out"

generate() {
  python3 - "$repo/$registry" "$repo/$report" <<'PY'
import json
import sys
from collections import Counter, defaultdict

registry_path, report_path = sys.argv[1:3]
registry = json.load(open(registry_path))
report = json.load(open(report_path))
counts = defaultdict(Counter)
for item in report.get("assertions", []):
    counts[item["id"]][item.get("status", "unknown")] += 1

def format_counts(counter):
    if not counter:
        return "not-run"
    return ", ".join(f"{key}:{counter[key]}" for key in sorted(counter))

def cell(value):
    return str(value).replace("|", "\\|").replace("\n", " ")

print("# DSLRaid Assertion Catalog\n")
print("<!-- generated by scripts/assertiongen.sh; do not edit by hand -->\n")
print(f"Registry version: {registry['assertion_version']}")
print(f"Validation source: {report['source']['core_ir']}\n")
print("| Assertion | Proposition | Code | Layer | Severity | Scope | Predicate | Result |")
print("| --- | --- | --- | --- | --- | --- | --- | --- |")
for item in sorted(registry["assertions"], key=lambda value: value["id"]):
    result = format_counts(counts[item["id"]])
    row = [item[key] for key in (
        "id", "proposition", "code", "layer", "severity", "scope", "predicate")]
    row.append(result)
    print("| " + " | ".join(cell(value) for value in row) + " |")
PY
}

cd "$repo"

case "$mode" in
  generate)
    mkdir -p "$(dirname "$target")"
    generate > "$target"
    echo "generated $out"
    ;;
  check)
    tmp="$(mktemp)"
    trap 'rm -f "$tmp"' EXIT
    generate > "$tmp"
    if ! diff -u "$target" "$tmp"; then
      echo "generated assertion catalog is stale: run scripts/assertiongen.sh generate" >&2
      exit 1
    fi
    echo "assertion generated doc ok"
    ;;
  *)
    echo "usage: scripts/assertiongen.sh [generate|check] [registry] [report] [out]" >&2
    exit 2
    ;;
esac
