#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$script_dir/lib/generated.sh"

dslraid_enter_repo

mode="${1:-check}"
out="${2:-docs/generated/generated-docs.md}"

generate() {
  python3 - "$repo/docs/generated" "$out" <<'PY'
import re
import sys
from pathlib import Path

root = Path(sys.argv[1])
out = sys.argv[2]

def cell(value):
    return str(value).replace("|", "\\|").replace("\n", " ")

print("# DSLRaid Generated Docs Index\n")
print("<!-- generated by scripts/gendocindex.sh; do not edit by hand -->\n")
print("Source: `docs/generated/*.md`\n")
print("| Document | Title | Generator |")
print("| --- | --- | --- |")
for path in sorted(root.glob("*.md")):
    rel = f"docs/generated/{path.name}"
    if rel == out:
        continue
    lines = path.read_text().splitlines()
    title = next((line[2:] for line in lines if line.startswith("# ")), "")
    marker = next((line for line in lines if "generated by" in line), "")
    match = re.search(r"generated by ([^;]+)", marker)
    generator = match.group(1) if match else "unknown"
    print(f"| [{path.name}]({path.name}) | {cell(title)} | `{cell(generator)}` |")
PY
}

dslraid_generated_case \
  "$mode" "$out" \
  "generated docs index is stale: run scripts/gendocindex.sh generate" \
  "generated docs index ok" \
  "usage: scripts/gendocindex.sh [generate|check] [out]"
