#!/usr/bin/env bash
set -euo pipefail

repo="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
mode="${1:-check}"
out="${2:-docs/generated/roadmap-index.md}"
target="$repo/$out"
source_doc="$repo/docs/roadmap.md"

generate() {
  awk '
  function clean(text) { gsub(/\|/, "\\|", text); return text }
  function flush() {
    if (title != "")
      printf "| %s | %s | %d | %d |\n", clean(title), clean(goal), items, exits
  }
  BEGIN {
    print "# DSLRaid Roadmap Index"
    print ""
    print "<!-- generated by scripts/roadmapgen.sh; do not edit by hand -->"
    print ""
    print "Source: docs/roadmap.md"
    print ""
    print "| Milestone | Goal | Scope Items | Exit Criteria |"
    print "| --- | --- | ---: | ---: |"
  }
  /^## Milestone / {
    flush()
    title = substr($0, 4)
    goal = ""; in_goal = 0; items = 0; exits = 0; in_exit = 0
    next
  }
  /^## / {
    flush()
    title = ""; next
  }
  /^Goal: / { goal = substr($0, 7); in_goal = 1; next }
  /^Exit criteria:/ { in_exit = 1; in_goal = 0; next }
  /^- / {
    if (title != "") {
      if (in_exit) exits += 1
      else items += 1
    }
    in_goal = 0; next
  }
  /^[[:space:]]*$/ { in_goal = 0; next }
  { if (in_goal) goal = goal " " $0 }
  END { flush() }
  ' "$source_doc"
}

cd "$repo"

case "$mode" in
  generate)
    mkdir -p "$(dirname "$target")"
    generate > "$target"
    echo "generated $out"
    ;;
  check)
    tmp="$(mktemp)"
    trap 'rm -f "$tmp"' EXIT
    generate > "$tmp"
    if ! diff -u "$target" "$tmp"; then
      echo "generated roadmap index is stale: run scripts/roadmapgen.sh generate" >&2
      exit 1
    fi
    echo "roadmap generated doc ok"
    ;;
  *)
    echo "usage: scripts/roadmapgen.sh [generate|check] [out]" >&2
    exit 2
    ;;
esac
