#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$script_dir/lib/generated.sh"

mode="${1:-check}"
out="${2:-docs/generated/roadmap-index.md}"

generate() {
  awk '
  function clean(text) { gsub(/\|/, "\\|", text); return text }
  function flush() {
    if (title != "")
      printf "| %s | %s | %d | %d |\n", clean(title), clean(goal), items, exits
  }
  BEGIN {
    print "# DSLRaid Roadmap Index"
    print "\n<!-- generated by scripts/roadmapgen.sh; do not edit by hand -->\n"
    print "Source: docs/roadmap.md\n"
    print "| Milestone | Goal | Scope Items | Exit Criteria |"
    print "| --- | --- | ---: | ---: |"
  }
  /^## Milestone / {
    flush(); title = substr($0, 4)
    goal = ""; in_goal = 0; items = 0; exits = 0; in_exit = 0
    next
  }
  /^## / { flush(); title = ""; next }
  /^Goal: / { goal = substr($0, 7); in_goal = 1; next }
  /^Exit criteria:/ { in_exit = 1; in_goal = 0; next }
  /^- / {
    if (title != "") {
      if (in_exit) exits += 1
      else items += 1
    }
    in_goal = 0; next
  }
  /^[[:space:]]*$/ { in_goal = 0; next }
  { if (in_goal) goal = goal " " $0 }
  END { flush() }
  ' "$repo/docs/roadmap.md"
}

dslraid_enter_repo
dslraid_generated_case \
  "$mode" "$out" \
  "generated roadmap index is stale: run scripts/roadmapgen.sh generate" \
  "roadmap generated doc ok" \
  "usage: scripts/roadmapgen.sh [generate|check] [out]"
