#!/usr/bin/env bash
set -euo pipefail

repo="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
mode="${1:-check}"
trace="${2:-examples/runscope/run-001.trace.json}"
coverage="${3:-examples/runscope/run-001.coverage.json}"
out="${4:-docs/generated/trace-catalog.md}"
target="$repo/$out"
generate() {
  python3 - "$repo/$trace" "$repo/$coverage" <<'PY'
import json, sys
from collections import Counter

trace = json.load(open(sys.argv[1]))
coverage = json.load(open(sys.argv[2]))
def cell(value):
    return str(value if value is not None else "").replace("|", "\\|").replace("\n", " ")

def row(values):
    print("| " + " | ".join(cell(value) for value in values) + " |")
run = trace["run"]
events = trace.get("events", [])
subjects = coverage.get("subjects", [])
print("# DSLRaid Trace Catalog\n")
print("<!-- generated by scripts/tracegen.sh; do not edit by hand -->\n")
print(f"Design IR: {trace['design_ir']['path']}")
print(f"Coverage IR: {coverage['design_ir']['path']}")
print(f"Run: {run['id']} ({run.get('environment', '')})")
print(f"Window: {run['started_at']} -> {run['ended_at']}\n")
print("## Trace Events\n")
print("| Event | Kind | Subject | Status | From | To | Duration ms |")
print("| --- | --- | --- | --- | --- | --- | ---: |")
for event in events:
    row([event["id"], event["kind"], event["subject"], event.get("status"),
        event.get("from"), event.get("to"), event.get("duration_ms")])
print("\n## Coverage Summary\n")
print("| Kind | Status | Subjects |")
print("| --- | --- | ---: |")
counts = Counter((item["kind"], item["status"]) for item in subjects)
for (kind, status), count in sorted(counts.items()):
    row([kind, status, count])
print("\n## Observed Subjects\n")
print("| Subject | Kind | Status | Count | Failure Rate | Last Seen |")
print("| --- | --- | --- | ---: | ---: | --- |")
observed = [item for item in subjects if item.get("count", 0) > 0]
for item in sorted(observed, key=lambda value: value["subject"]):
    row([item["subject"], item["kind"], item["status"], item["count"],
        item["failure_rate"], item.get("last_seen")])
PY
}
cd "$repo"
case "$mode" in
  generate)
    mkdir -p "$(dirname "$target")"
    generate > "$target"
    echo "generated $out"
    ;;
  check)
    tmp="$(mktemp)"
    trap 'rm -f "$tmp"' EXIT
    generate > "$tmp"
    if ! diff -u "$target" "$tmp"; then
      echo "generated trace catalog is stale: run scripts/tracegen.sh generate" >&2
      exit 1
    fi
    echo "trace generated doc ok"
    ;;
  *)
    echo "usage: scripts/tracegen.sh [generate|check] [trace] [coverage] [out]" >&2
    exit 2
    ;;
esac
