#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$script_dir/lib/generated.sh"

mode="${1:-check}"
trace="${2:-examples/runscope/run-001.trace.json}"
coverage="${3:-examples/runscope/run-001.coverage.json}"
out="${4:-docs/generated/trace-catalog.md}"

generate() {
  python3 - "$repo/$trace" "$repo/$coverage" <<'PY'
import json, sys
from collections import Counter

trace = json.load(open(sys.argv[1]))
coverage = json.load(open(sys.argv[2]))
def cell(value):
    return str(value if value is not None else "").replace("|", "\\|").replace("\n", " ")

def row(values):
    print("| " + " | ".join(cell(value) for value in values) + " |")
run = trace["run"]
events = trace.get("events", [])
subjects = coverage.get("subjects", [])
print("# DSLRaid Trace Catalog\n")
print("<!-- generated by scripts/tracegen.sh; do not edit by hand -->\n")
print(f"Design IR: {trace['design_ir']['path']}")
print(f"Coverage IR: {coverage['design_ir']['path']}")
print(f"Run: {run['id']} ({run.get('environment', '')})")
print(f"Window: {run['started_at']} -> {run['ended_at']}\n")
print("## Trace Events\n")
print("| Event | Kind | Subject | Status | From | To | Duration ms |")
print("| --- | --- | --- | --- | --- | --- | ---: |")
for event in events:
    row([event["id"], event["kind"], event["subject"], event.get("status"),
        event.get("from"), event.get("to"), event.get("duration_ms")])
print("\n## Coverage Summary\n")
print("| Kind | Status | Subjects |")
print("| --- | --- | ---: |")
counts = Counter((item["kind"], item["status"]) for item in subjects)
for (kind, status), count in sorted(counts.items()):
    row([kind, status, count])
print("\n## Observed Subjects\n")
print("| Subject | Kind | Status | Count | Failure Rate | Last Seen |")
print("| --- | --- | --- | ---: | ---: | --- |")
observed = [item for item in subjects if item.get("count", 0) > 0]
for item in sorted(observed, key=lambda value: value["subject"]):
    row([item["subject"], item["kind"], item["status"], item["count"],
        item["failure_rate"], item.get("last_seen")])
PY
}

dslraid_enter_repo
dslraid_generated_case \
  "$mode" "$out" \
  "generated trace catalog is stale: run scripts/tracegen.sh generate" \
  "trace generated doc ok" \
  "usage: scripts/tracegen.sh [generate|check] [trace] [coverage] [out]"
