#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$script_dir/lib/generated.sh"
source "$script_dir/lib/lisp-runtime.sh"

dslraid_enter_repo

mode="${1:-check}"
out="${2:-docs/generated/verification-github-actions.json}"

generate() {
  dslraid_lisp_eval \
    '(write-string (dslraid.agent::emit-verification-github-actions-json))' |
    python3 -m json.tool
}

validate_actions() {
  python3 - "$repo/$out" <<'PY'
import json, os, sys
data = json.load(open(sys.argv[1]))
expected = {
    ".github/workflows/ci.yml", ".github/workflows/golden.yml",
    ".github/workflows/security.yml", ".github/workflows/pages.yml",
    ".github/workflows/verification.yml", ".github/workflows/release.yml",
}
errors, seen = [], set()
for row in data.get("workflows", []):
    seen.add(row["workflow"])
    if not os.path.exists(row["workflow"]):
        errors.append(f"missing workflow {row['workflow']}")
        continue
    text = open(row["workflow"]).read()
    if "permissions:" not in text:
        errors.append(f"{row['id']} missing permissions block")
    for item in row.get("permissions", []):
        if item not in text:
            errors.append(f"{row['id']} missing permission {item}")
    if row.get("generated"):
        header = f"# generated by {row['generator']}"
        if not any(header in line for line in text.splitlines()[:3]):
            errors.append(f"{row['id']} missing generated header")
        if not os.path.exists(row["generator"]):
            errors.append(f"{row['id']} missing generator")
    for item in row.get("evidence", []):
        if not os.path.exists(item):
            errors.append(f"{row['id']} missing evidence {item}")
if seen != expected:
    errors.append(f"workflow suite mismatch: {sorted(expected - seen)}")
if not data.get("closure_rules"):
    errors.append("github actions suite manifest has no rules")
if errors:
    print("\n".join(errors), file=sys.stderr)
    sys.exit(1)
print("verification GitHub Actions suite check ok")
PY
}

case "$mode" in
  generate) mkdir -p "$(dirname "$repo/$out")"; generate > "$repo/$out"; echo "generated $out" ;;
  check)
    dslraid_generated_check "$out" \
      "generated GitHub Actions suite is stale: run scripts/verificationactionsgen.sh generate" \
      "verification GitHub Actions suite generated output ok"
    validate_actions ;;
  *) echo "usage: scripts/verificationactionsgen.sh [generate|check] [out]" >&2; exit 2 ;;
esac
