use dslraid_core::{Artifact, CoreIr, Derivation};

use super::table;

pub(super) fn write(out: &mut String, ir: &CoreIr) {
    write_derivations(out, &ir.derivations);
    write_artifacts(out, &ir.artifacts);
}

fn write_derivations(out: &mut String, derivations: &[Derivation]) {
    out.push_str("## Derivations\n\n");
    table::header(out, &["Derivation", "Source", "Rule", "Targets"]);
    for derivation in derivations {
        table::row(
            out,
            &[
                derivation.id.clone(),
                derivation.source.clone(),
                derivation.rule.id.clone(),
                derivation
                    .targets
                    .iter()
                    .map(|target| target.artifact.clone())
                    .collect::<Vec<_>>()
                    .join(", "),
            ],
        );
    }
    out.push('\n');
}

fn write_artifacts(out: &mut String, artifacts: &[Artifact]) {
    out.push_str("## Artifacts\n\n");
    table::header(out, &["Artifact", "Kind", "Path", "Generated By"]);
    for artifact in artifacts {
        table::row(
            out,
            &[
                artifact.id.clone(),
                artifact.kind.clone(),
                artifact.path.clone(),
                artifact.generated_by.clone().unwrap_or_default(),
            ],
        );
    }
    out.push('\n');
}
