use dslraid_core::{CoreIr, Fsm};

use super::table;

pub(super) fn write(ir: &CoreIr) -> String {
    let mut out = String::new();
    out.push_str("# DSLRaid FSM Catalog\n\n");
    out.push_str("<!-- generated by dslraid doc fsm-catalog; do not edit by hand -->\n\n");
    out.push_str("Source project: ");
    out.push_str(&ir.project.id);
    out.push_str("\n\n");
    table::header(
        &mut out,
        &[
            "FSM",
            "Subject",
            "States",
            "Initial",
            "Terminal",
            "Transitions",
        ],
    );
    for fsm in &ir.fsms {
        table::row(&mut out, &row(fsm));
    }
    out
}

fn row(fsm: &Fsm) -> [String; 6] {
    [
        fsm.name.clone(),
        fsm.id.clone(),
        fsm.states.len().to_string(),
        initials(fsm),
        terminals(fsm),
        fsm.transitions.len().to_string(),
    ]
}

fn initials(fsm: &Fsm) -> String {
    fsm.states
        .iter()
        .filter(|state| state.initial)
        .map(|state| state.id.as_str())
        .collect::<Vec<_>>()
        .join(", ")
}

fn terminals(fsm: &Fsm) -> String {
    fsm.states
        .iter()
        .filter(|state| state.terminal)
        .map(|state| state.id.as_str())
        .collect::<Vec<_>>()
        .join(", ")
}
