use dslraid_core::CoreIr;

use super::table;

pub(super) fn write(out: &mut String, ir: &CoreIr) {
    out.push_str("# ");
    out.push_str(&ir.project.name);
    out.push_str("\n\n");
    out.push_str("<!-- generated by dslraid doc generate; do not edit by hand -->\n\n");
    out.push_str("## Summary\n\n");
    table::header(out, &["Metric", "Count"]);
    table::row(out, &row("FSMs", ir.fsms.len()));
    table::row(out, &row("Compositions", ir.compositions.len()));
    table::row(out, &row("Projections", ir.projections.len()));
    table::row(out, &row("Derivations", ir.derivations.len()));
    table::row(out, &row("Artifacts", ir.artifacts.len()));
    out.push('\n');
}

fn row(label: &str, count: usize) -> [String; 2] {
    [label.to_string(), count.to_string()]
}
