use anyhow::{bail, Context, Result};
use std::{fs, path::Path};

const GENERATED_DOCS: &str = "docs/generated";

pub(super) fn check() -> Result<()> {
    for entry in fs::read_dir(GENERATED_DOCS).context("read generated docs")? {
        let path = entry?.path();
        if path.extension().and_then(|value| value.to_str()) == Some("md") {
            check_doc(&path)?;
        }
    }
    Ok(())
}

fn check_doc(path: &Path) -> Result<()> {
    let content = fs::read_to_string(path).with_context(|| format!("read {}", path.display()))?;
    let marker = content
        .lines()
        .find_map(generator_marker)
        .ok_or_else(|| anyhow::anyhow!("{} has no generated-by marker", path.display()))?;
    check_generator(path, marker)
}

fn generator_marker(line: &str) -> Option<&str> {
    let prefix = "<!-- generated by ";
    line.strip_prefix(prefix)
        .and_then(|rest| rest.strip_suffix("; do not edit by hand -->"))
}

fn check_generator(path: &Path, generator: &str) -> Result<()> {
    if generator.starts_with("dslraid ") {
        return Ok(());
    }
    if generator == "go run ./cmd/repoctl docs generate" && Path::new("cmd/repoctl").is_dir() {
        return Ok(());
    }
    if generator.starts_with("scripts/") && Path::new(generator).exists() {
        return Ok(());
    }
    bail!(
        "{} has non-executable generator marker: {}",
        path.display(),
        generator
    )
}
